### ISSUE TITLE
Column auto-width support

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#106]
Double click on column edge should lead for column width calculation based on number of symbols of the longest element.

**Comment by bbbford** [comment]
@revolist Great library! I have begun implementing it today. 

May I also suggest a property at the grid level, i.e. "autosize" that will automatically size all columns by default.

**Comment by revolist** [comment]
An auto-size feature takes quite many resources for huge data calculation. The user has to consider going with it. In the future, we shall develop some templates for different project types, for example, if you are not going with huge data you still can go with auto-width by default. But now the main focus on performance.

@bbbford let me know if you need some help there or an idea.

**Comment by revolist** [comment]
@bbbford autosize will be next in order. Today just finished minimal plugin support for column types.

**Comment by revolist** [comment]
Feature added.
https://revolist.github.io/revogrid/guide/autosize.html
