### ISSUE TITLE
How to pass typed key to cellEditor?

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#125]
Let's say you have a select input as an editor and you want to open the select with the typed text... like if you have a cell that has a selection of countries and you want to type s and open the select with the first country with an "S". The same way you clicked "edit", then clicked the select itself, and when opened typed an "S".

**Comment by kas84** [comment]
Figured you can do:
```
const selectElement=document.getElementById('whatever')
selectElement.value=this.editCell.val;
```
on `componentDidRender function`

**Comment by revolist** [comment]
Thank you, going to provide some more samples in the nearest future for all of it.
