### ISSUE TITLE
Vue.js wrapper not re-rendering stencil.js component

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#126]
I made a wrapper (Grid.vue) based on your docs like this:

```
<script>
    import Vue from 'vue';
    Vue.config.ignoredElements = [/revo-\w*/]; // Set ignore web-component and avoid parsing it as vuejs
    export default {
        name: 'grid',
        props: ['canFocus', 'colSize', 'columns', 'editors', 'frameSize', 'pinnedBottomSource', 'pinnedTopSource', 'range',
        'readonly', 'refresh', 'resize', 'rowClass', 'rowSize', 'source', 'theme'],
        data() {
            return {
                asc: true
            };
        },
        render: function (createElement) {
            console.log("rendering grid",this.source)
            return createElement(
                'revo-grid',
                {
                   class: "grid-component",
                   domProps: this.$props
                },
            );
        },
    }
</script>
```

However, if i do:
```
<Grid v-if="someReactiveData == 'first'"/>
<Grid v-if="someReactiveData == 'second'"/>
```

When I change the variable from 'first' to 'second' the Grid component doesn't get re-rendered.
But if I change it to something it doesn't exist ('third' for example), causes the Grid element to banish and when I change the variable back to 'second' (after the Grid element not being rendered at all) then it renders just fine.

The render function on Grid.vue gets called though.
```
Grid.vue:14 rendering grid (20) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Observer]
Grid.vue:14 rendering grid (6) [{…}, {…}, {…}, {…}, {…}, {…}, __ob__: Observer]
```

**Comment by revolist** [comment]
thank you for the issue, I'll check.

**Comment by revolist** [comment]
Hello @kas84 , your issue quite common for vuejs, all you have to do just specify key.
Check this link here as working example:
https://codesandbox.io/s/data-vue-test-3wkzi?file=/src/App.vue

Also I recommend for future issue if you'd like to get a quicker answer please post real live sample.

And for your benefit we've created vuejs wrapper for the grid, it's powerful and very convenient:
`npm i @revolist/vue-datagrid`

**Comment by kas84** [comment]
Didn't know! I'm a Vue newbie! Thanks for your response & for the wrapper :)
