### ISSUE TITLE
Supporting CTRL + Z

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#128]
Hi, are you planning on supporting undo with CTRL+ Z?

**Comment by revolist** [comment]
Hello, this is Grid history feature, it's quite complicated but there is a future plan for it for sure.

**Comment by niklashaa** [comment]
Hi, are there any news on this?

**Comment by APMU** [comment]
Hi,

This is a nice and important feature (ctrl Z and crtl R). 

I wish you can implement. 

Thanks.

**Comment by dennisgeerts** [comment]
Any further updates on this?
