### ISSUE TITLE
Custom Row Headers

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#130]
As far as I am concern, row headers only display numbers and are not customizable, am I right? 

Let's say in your example here https://revolist.github.io/revogrid/ you want name to be a row header so that's not selectable, is that possible?

**Comment by revolist** [comment]
Hello,

We didn't provide template for row headers yet.
What are you trying to achieve is better to be done with fixed column + prevent focus on this column:


https://revolist.github.io/revogrid/guide/column.pinned.html

https://revolist.github.io/revogrid/guide/api.html#properties
`beforeCellFocus`

` beforeFocus(e: CustomEvent<{model: {summaryType?: string}}>): void {
    if (e.detail?.model?.summaryType === SPACER_HEADER) {
      e.preventDefault();
    }
  }`

**Comment by kas84** [comment]
This method does work on click, but not on selecting with arrows, apparently

**Comment by revolist** [comment]
It's an issue then! thank you for catch

**Comment by jorgemmsilva** [comment]
Hi, this is quite a desirable feature. Do you have any ETA for header templates or some sort of development roadmap?
I can try to contribute, but haven't delved into the code yet. Do you have some pointers on implementing custom headers, or some sort of contributors guide?
Thanks

**Comment by revolist** [comment]
@jorgemmsilva, it's quite easy to add, same as a cell template, need to extend row definition property `rowDefinitions`. We'll add it at the nearest time if you do not get it first. Our main features are represented on Project kanban https://github.com/revolist/revogrid/projects/1

**Comment by revolist** [comment]
@jorgemmsilva , @kas84 check 
https://github.com/revolist/revogrid/releases/tag/v1.9.5

**Comment by Magenta94** [comment]
Is this feature implemented? Can't find it on the docs. I'm using VueJS.

**Comment by revolist** [comment]
@Magenta94, yes, it should work this way:
```
const grid = document.querySelector('revo-grid');
grid.rowHeaders = {
  size: 200
};
```
For vuejs better post in vue repository, but implementation quite similar:

```vue
<v-grid :rowHeaders="rowHeaders"/>
```
```js
{
  data() {
    return {
       rowHeaders:  {
          size: 200
        };
    }
  }
}
```
