### ISSUE TITLE
Discerning between double click to edit and type to edit

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#131]
On a custom cell Editor, how can I discern if the user is editing because it selected the cell and started typing or the user double clicked the cell?

What I want to achieve is the following:

On a autocomplete element if the user starts typing I don't want to use this focus listener that automatically selects the text
```
  componentDidRender() {
      ....
      const inputElement = document.getElementById('autocomplete-input')
      let focusedElement
      inputElement.addEventListener('focus', (ev) => {
        if (focusedElement) return
        focusedElement = inputElement
        setTimeout(function () {
          focusedElement.select()
        }, 0) //select all text in any field on focus for easy re-entry. Delay sightly to allow focus to "stick" before selecting.
      })
      setTimeout(function () {
        inputElement.focus()
      }, 0)
    }, // optional, called after component rendered
```

For example, let's say the autocomplete is a country autocomplete, and the previous value is "Estonia", the user double clicks to edit, I want to select all the text so that when he start's typing "Spain"... "Estonia", gets removed, but, when the user starts typing right away, I don't want to select at All, because otherwise, on the first onFocus, we would Select "S", and when the user continues typing, it would remove the "S" and would type "pain".

**Comment by kas84** [comment]
Even though it might not be ideal, on componentDidRender I am doing this to know if it was edited by typing or doubleclick.

I'm doing == and not === because  this.editCell.val will be a string but this.editCell.model[prop] could be a number and I want 2 == "2"

```
      const prop=this.editCell.prop
      const val=this.editCell.val
      if (this.editCell?.model[prop]==val){
        console.log("IT MUST BE A DOUBLE-CLICK EDIT")
      }else{
        console.log("IT MUST BE A TYPING EDIT")
      }
```

**Comment by kas84** [comment]
any plans on this? this implementation is far from ideal, because if the edited value is a single letter you cannot know if it's a double click edition or a type edition

**Comment by revolist** [comment]
ComponentDidRender is way too late for it. You have setup data in render and add extra in componentDidRender.

**Comment by revolist** [comment]
@kas84 check select functionality is that the one you are talking about:
https://revolist.github.io/revogrid/demo/
