### ISSUE TITLE
Handle mac 'Enter' key

### ISSUE THREAD

**Issue by bbbford** [revolist/revogrid#133]
A full-sized mac keyboard has an 'Enter' key by the number pad. When editing a cell in revogrid, pressing this 'Enter' key should result in the same behavior as pressing the 'Return' key.

**Comment by bossevn** [comment]
The same occurs in Windows. All the other keys work properly, but not the 'Enter' one

**Comment by revolist** [comment]
@bbbford, @bossevn fixed.

**Comment by sonikdesign** [comment]
Problems with Enter key in an Android tablet. In my case: Lenovo TB-X606X. Nothing happen, the cursor remains in the cell input.
_beforeedit_ event doesn't happen.
