### ISSUE TITLE
Use with grid layout ?

### ISSUE THREAD

**Issue by MentalGear** [revolist/revogrid#135]
Would it be possible to use this with an icon grid layout, ios style ?

**Comment by revolist** [comment]
@MentalGear , not sure what is your question about. You can put any icons inside of grid cells and much more.

**Comment by MentalGear** [comment]
Sorry, could be clearer. I mean an grid layout like this, or maybe your plugin is only for tables ?

<img width="367" alt="Screenshot 2020-11-25 at 19 11 54" src="https://user-images.githubusercontent.com/2837147/100266518-3e102000-2f52-11eb-91f1-1087ac573f77.png">

**Comment by revolist** [comment]
No, it’s not for tables only
Revo-grid can make any layout you like and handle huge amount of data

**Comment by MentalGear** [comment]
Thanks for the reply, after checking the api guide, I couldn't however find how to make such a grid icon layout, only the standard table layout is described. I would much appreciate an example. Thx.

**Comment by revolist** [comment]
@MentalGear check this sample out:
https://codesandbox.io/s/vue-grid-icons-3vuuj?file=/src/App.vue

**Comment by MentalGear** [comment]
Cool, thank you for the example! It still has the table header, and row hightlight, but I assume those can be toggled off via api/css ?

**Comment by revolist** [comment]
Column header can be hidden with css. Just set it height to 0
