### ISSUE TITLE
remove table sort

### ISSUE THREAD

**Issue by jorgemmsilva** [revolist/revogrid#140]
Hi, some basic customization features which I think are lacking:

1) ability to disable edit on columns definition
2) removing sort after a table has been sorted (third consecutive click could remove the table sort)

on a separate note: I've noticed the grid is not ignoring keyboard shortcuts when having a cell selected. example: select a cell and do `cmd+L` to edit the url on the page, notice that the cell value changes.

I'm happy to try to help you improve this if you can give me some pointers.

**Comment by srsad** [comment]
Hi @jorgemmsilva 
If I understand you correctly, you can disable editing for some columns by setting them to `readonly: true`, for example.
```
//...
  {
    name: 'Profit',
    prop: 'profit',
    pin: 'colPinEnd',
    sortable: false,
    readonly: true,
    size: 80
  },
// ...
```

**Comment by jorgemmsilva** [comment]
Thank you @srsad, I've missed that prop.

**Comment by jorgemmsilva** [comment]
Regarding "2. removing table sorting":

I would assume preventing the default behaviour of the `beforeSorting` event, and sending a new event with `{order: ''}` could do the trick, but the following doesn't seem to work:

```js
              onBeforeSorting={(e) => {
                const { detail: { column, order } } = e
                if (order === 'asc' && column.order === 'desc') {
                  e.preventDefault()
                  e.target.dispatchEvent(
                    new CustomEvent(e.type, { ...e, detail: { ...e.detail, order: null } }),
                  )
                }
              }}
```

is there any straightforward way to do this? Thanks.

**Comment by revolist** [comment]
@jorgemmsilva not very clear what you are trying to achieve? 
Are you aiming to override order?
If so you can do:

```
onBeforeSorting={(e) => {
  if (order === 'asc' && column.order === 'desc') {
    e.detail.order = null;
  }
}}
```

if you want to avoid sorting just use ```e.preventDefault()```

**Comment by Buroni** [comment]
@revolist The above prevents sorting, but doesn't remove the arrow icon from the column header. Is there a straightforward way to do this?

Also I think the type definition for `e.detail.order` should be updated to support `null`.

**Comment by Buroni** [comment]
@revolist The above prevents sorting, but doesn't reset the column order to its initial state. Is there a straightforward way to do this?

**Comment by revolist** [comment]
@Buroni, 

/**
 * lifecycle
 * 1) @event beforeSorting - sorting just started, nothing happened yet
 * 2) @metod updateColumnSorting - column sorting icon applied to grid and column get updated, data still untiuched
 * 3) @event beforeSortingApply - before we applied sorting data to data source, you can prevent data apply from here
 * 4) @event afterSortingApply - sorting applied, just finished event
 * 
 * If you prevent event it'll not reach farther steps
 */

I suggest to check sorting.plugin.ts file, it's quite easy to read.

**Comment by Buroni** [comment]
@revolist Thanks for the info. My question isn't about how to prevent the sorting event from being applied, but rather how to reset the column order to the initial order. For example

* First click - sort `asc`
* Second click - sort `desc`
* Third click - reset the column order to its initial order

**Comment by revolist** [comment]
@Buroni, feature makes sense for sure.
If you provide us with PR we'll review it and approve.

Got your idea.
Yes, for now the only custom way is to prevent beforeSorting and apply your own in such case.
Need update source code to make it work right.

**Comment by ojaylu** [comment]
The rows still seem to be sorted on the third click. Has this feature been implemented yet? I'm using the React version. Thanks.

**Comment by revolist** [comment]
> The rows still seem to be sorted on the third click. Has this feature been implemented yet? I'm using the React version. Thanks.

Seems an issue, reopening for investigation

**Comment by Buroni** [comment]
It was implemented, but seems like there has been a regression. I may have time to look into this next week if someone else doesn't pick it up

**Comment by revolist** [comment]
Ty @Buroni!
It was, we've been testing it and it's was working, something changed. I'll change too, depend on availability.
