### ISSUE TITLE
Ability to have different rowSize per row 

### ISSUE THREAD

**Issue by angelblanco** [revolist/revogrid#141]
Hello! 

Thank you for this amazing library, we are really impressed about the performance of the grid component.

I spend some time yesterday seeing if it's possible right now to have rows of different height on the same table. Either with styling or on the row definition.

Thanks!

**Comment by revolist** [comment]
Hello @angelblanco , thank you for your feedback. There is a way to setup row size for sure:
check for `rowDefinitions` property in API doc:

https://revolist.github.io/revogrid/guide/api.html#properties
```
type RowDefinition = {
    type: DimensionRows;
    size: number;
    index: number;
  };
```

```
rowDefinitions = [{
        type: 'row',
        0,
        size: 45
      }];

<revogrid rowDefinitions={rowDefinitions}/>
```

**Comment by revolist** [comment]
Document was updated:
https://revolist.github.io/revogrid/guide/rows.size.html
