### ISSUE TITLE
support mouse selection range feature 

### ISSUE THREAD

**Issue by SolidZORO** [revolist/revogrid#142]
Why was the mouse selection range feature removed in later versions?

I see that https://github.com/revolist/revogrid/commit/40de4843301082d9fe90b5788c414a76a525069e is the last version that supports mouse selection range ([online demo](https://rgp-hl.vercel.app/)), what is the problem that abandoned this feature? 

Is there any plan to support it in the future?

**Comment by revolist** [comment]
Hello @SolidZORO 
What are you referring to by Mouse Selection?
Is that focusing multiple cell with mouse drag without actual selection them with blue handler?

We are not abandoning it, I think it's rather a bag that it was removed.
Will check it after Filter feature/Trim rows release.

Thank you.

**Comment by SolidZORO** [comment]
Thank you very much for your reply, it solved my confusion. And thanks again for revogrid, it's one of the best performing forms I've seen so far.

**Comment by revolist** [comment]
> Thank you very much for your reply, it solved my confusion. And thanks again for revogrid, it's one of the best performing forms I've seen so far.

Thank you for your feedback, it's very appreciated.

**Comment by revolist** [comment]
Range selection with the mouse is present in the latest version

**Comment by balazs-zsoldos** [comment]
@revolist Is this feature testable on the demo site? If yes, it seems that selection is possible vertically or horizontally. But not a rectangle.

Please also note, that after showing revogrid as possible technology for a customer, the first question was: Is it possible to select multiple cells and ranges and paste the same value into it like in excel? I was surprised as I did not know such feature existed, but they said it was very useful for them as they saw before pasting a value where they wanna pate it. When I have time, I think I will help contributing this feature, but for that, it would be important to keep in mind that mutliple cells should be selectable (not next to each other), so future improvements and new APIs should not make harder to implement this feature.

**Comment by revolist** [comment]
Hello @balazs-zsoldos,
It's possible to select a rectangle but only in 2 sets, meaning if you started to drag in a vertical or horizontal plane you'll have to keep it that way, we specially made it as it is to simplify the development of this feature to decrease the number of possible scenarious. It's not hard to develop extended selection, but it will require extra time for this feature.

> Is it possible to select multiple cells and ranges and paste the same value into it like in excel?
Out of box, it is not possible, but it's easy to achieve. All you have to do track selected area and input values. Also should be requested as separate feature.

**Comment by van-huyen** [comment]
Hi everyone,

How can i select multi cells range in now version of revogrid? Like first question of this issue

https://user-images.githubusercontent.com/83264685/119283713-d294da00-bc78-11eb-8ba8-4f695f2f8e5f.mp4

Thanks

**Comment by natee** [comment]
> Hi everyone,
> 
> How can i select multi cells range in now version of revogrid? Like first question of this issue
> 
>  Revo.Grid.Component.Demo.-.Google.Chrome.2021-05-24.10-12-02.mp4 
> Thanks

You can press and hold the shift button

**Comment by van-huyen** [comment]
thanks natee,
It's working with "press and hold the shift button".
but i think it is not good a UX
