### ISSUE TITLE
TIP: Computed column sorting and formatting

### ISSUE THREAD

**Issue by illogikal** [revolist/revogrid#143]
I wanted to have columns that are computed from fields in the model, and have them be sortable. This is how I did it. I can add it to the readme if it would be helpful.

```
computableFnChange = props => {
	val = props.model.ONE_FIELD - props.model.OTHER_FIELD
	props.model[props.prop] = val
	return {
		raw: val,
		formatted: numeral(val).format('0,0.000')	
	}
}
#columns...
	{
		name: 'Test',
		prop: '___test',
		sortable: true,
		order: 'asc',
		cellTemplate: (createElement, props) => createElement('div', {
				style: { 
					color: colorFunctionBasedOnValue(computableFnChange(props).raw) 
				}
			}, computableFnChange(props).formatted)
	}
```

I want to have the color depend on whether the value is positive or not, but I also want it formatted. This works because the data structures are not immutable and it's a bit hacky but it works. I name the fields something that should not collide with actual fields on the model. This way is quite extendable and could allow for external datasources merging on the table.

**Comment by revolist** [comment]
Hello @illogikal
I'm not sure I understand the whole idea you were asking about.

There are several ways to achieve it, what u've done - you provided a helper function.
I would suggest only do not call it twice as you did:


```
cellTemplate: (createElement, props) => createElement('div', {
				style: { 
					color: colorFunctionBasedOnValue(computableFnChange(props).raw) 
				}
			}, computableFnChange(props).formatted)
```

better

```
cellTemplate: (h, props) => {
   const computed = computableFnChange(props); // it'll have 1 call, not 2 per cell
   return h('div', {
				style: { 
					color: colorFunctionBasedOnValue(computed.raw) 
				}
			}, computed.formatted)
}
```

Yet there is one more un documented property in column: `cellProperties`.

```
{
  cellProperties({ val }) {
       return colorFunctionBasedOnValue(val);
  },
  cellTemplate(h, {val}) {
    return numeral(val).format('0,0.000');
  }
}
```

**Comment by illogikal** [comment]
I was mashing the calculated row into the array on render. It's not the best route at all, but the cellproperties field sounds like a much better plan. Does the sorting function use the cellproperties output?

**Comment by revolist** [comment]
@illogikal nope, sorting doesn't use render function at all, it's based on data in source object.

**Comment by revolist** [comment]
Closing 'coz of in activity.
Let us know is there any way we can help,
