### ISSUE TITLE
2.0 bug - sorting a grid with a pinned column

### ISSUE THREAD

**Issue by bbbford** [revolist/revogrid#145]
In 2.0.2, when sorting a grid that has a pinned column, the rows within the pinned column are not in the correct order after a sort. If you click into the grid after a sort, the pinned column then becomes correct.

Likewise, if you sort the pinned column, the rest of the grid is not properly sorted.

Repro:
[https://codesandbox.io/s/revogrid-vueeditor-forked-qspve?file=/src/App.vue](https://codesandbox.io/s/revogrid-vueeditor-forked-qspve?file=/src/App.vue)

**Comment by revolist** [comment]
Thank you for quick reaction @bbbford , and a very nice sample to reproduce.
https://github.com/revolist/revogrid/releases/tag/2.0.3
