### ISSUE TITLE
ColumnTypes not working?

### ISSUE THREAD

**Issue by tobiasgraeber** [revolist/revogrid#146]
Hi, 

i´m trying to use the column types with vue js, for example date, as described here https://revolist.github.io/revogrid/guide/column.types.html . but they do not work / nothing happens.

Here you can find my prepared fiddle...

https://codesandbox.io/s/optimistic-gates-21y2i?fontsize=14&hidenavigation=1&theme=dark
 
Could you maybe also provide the full code for this demo https://revolist.github.io/revogrid/ in the repository (unminified) or as a fiddle? I also would like to know, how to add a checkbox to each row...

**Comment by revolist** [comment]
Hello @tobiasgraeber 
Things are much easier, you just don't need extra array around column types.

Please check here:

https://codesandbox.io/s/vue-grid-date-plugin-6wudi?file=/src/App.vue
