### ISSUE TITLE
External library resetting sort

### ISSUE THREAD

**Issue by illogikal** [revolist/revogrid#153]
I am using https://github.com/fnando/sparkline to create spark lines after every header sort and source change. When I run the spark line lib, it works fine, but for some reason it removes the 'asc/desc' class on the relevant column. It doesn't change the sort order but it removes the class and the arrow icon. This is bad because I then have to double click the sort header to get descending. The sparkline lib doesn't affect the header at all so I guess there is a listener on the body of revogrid somewhere? What would be the best way to address this? I can provide a minimal example if you need.

**Comment by revolist** [comment]
Hello @illogikal , it'll be faster to process if you provide sample of problem you have.
For example:
https://codesandbox.io/s/revogrid-vueeditor-bxpq0?file=/src/SampleEditor.vue

**Comment by illogikal** [comment]
It's fine, I was doing something wrong on my side, and I fixed it. I was setting the columns of the grid on every render and it was removing the sort. I've fixed it, thanks!
