### ISSUE TITLE
Feature: Drag to select multiple cells

### ISSUE THREAD

**Issue by snird** [revolist/revogrid#158]
In Excel and other spreadsheet programs, including web-based such as google spreadsheet or `handsontable` tool -
You click and drag to select multiple cells.

Selecting multiple cells is possible already, by selecting a cell, holding shift, and selecting the finish cell.
It is just about implementing the intuitive drag functionality.

I might implement it myself if I'll find time on some weekend, but anyway it is here to document the feature.

**Comment by gongjiaji** [comment]
Please consider adding this function

**Comment by balazs-zsoldos** [comment]
+1

**Comment by revolist** [comment]
I think we are talking about same feature here

https://github.com/revolist/revogrid/issues/142

**Comment by revolist** [comment]
@gongjiaji , @balazs-zsoldos  was added in the latest versions, follow #142
