### ISSUE TITLE
Mobile actions support and fixed/pinned itmes syncronization

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#159]
Provide better mobile support with deep action UX.

- Currently, there is a weak point when we drag with touch synchronization of panels isn't smooth.

- Edit and resize actions can be improved.

**Comment by defghy** [comment]
Same problem. Not smooth in mobile when pinned item exist

**Comment by revolist** [comment]
Hello @defghy, currently mobile version is a second priority for us. But we are checking options to solve this particular case for you.

**Comment by defghy** [comment]
Thanks a lot for great effort.
