### ISSUE TITLE
Provide template usage so every one can start with revo-grid in a second.

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#160]
Provide template usage so everyone can start with revo-grid in a second.

Usage examples:

## List
   - List with checkboxes and select all header;
   - List with icons;

## Grid
- Basic grid;
- Grid with checkboxes;
- Grid with draggable rows;
- Grid with column grouping;
- Grid with grouping;
- Grid sorting;
- Grid multi sorting;
- Grid export;
- Grid layout as virtual layout for shopping;
- Grid layout with icons;

## Kanban
- Grid as kanban;
- Dragging between columns;

## Advanced
- Grid plugin creation;
- Grid custom column type creation;

Anything else?

**Comment by JulienGrv** [comment]
I think [storybook](https://storybook.js.org/) could be used for this
