### ISSUE TITLE
Pinned column cell overflow

### ISSUE THREAD

**Issue by derekchan916** [revolist/revogrid#162]
I was wondering if there would be any way for a cell in the pinned column to overflow. In the image linked below, I actually made the cell focus border around the cell itself, and hid the revogrid focus state element. 

However, in doing so (actually with both methods), the blue border can not overflow out of the pinned column because of the overflow styling.

![image](https://user-images.githubusercontent.com/12720511/106391537-d92ce680-6428-11eb-9c87-0c80cf0c6eeb.png)

Is there any way we can allow for the blue border to overflow?

**Comment by revolist** [comment]
@derekchan916, why do you need to replace the existing focus? What is the problem with it?

Todo what you requested;

```
.data-cell {
 box-shadow: 0 1px red, -1px 0 red inset, 1px 0 red inset, 0 1px red inset;
}
```

<img width="1356" alt="Screen Shot 2021-02-02 at 6 43 15 PM" src="https://user-images.githubusercontent.com/64810943/106677533-dfd17000-6586-11eb-9643-b2dc942e18c9.png">
