### ISSUE TITLE
Error using VGridVueTemplate

### ISSUE THREAD

**Issue by leyenda** [revolist/revogrid#164]
Hello, first thank you for your work in this awesome package.

I've been testing revogrid with vue, and an error appears to happen when I use VGridVueTemplate as a cellTemplate.
It renders fine, but when I scroll horizontally in console I see this error:

> TypeError
> Cannot read property 'appendChild' of null

And it doesn't render the other columns.

I've made a sandbox for you to test it. I am using the latest version 2.9.2

[Code Sandbox](https://codesandbox.io/s/revogrid-vuecomponent-forked-14d2y)

**Comment by revolist** [comment]
@leyenda 
Fixed in 2.9.3! Thank you for checking it out.
