### ISSUE TITLE
Sample for trimmedRows

### ISSUE THREAD

**Issue by leyenda** [revolist/revogrid#165]
Greetings everyone. 
I am having a hard time implementing a custom filter with trimmedRows. The follow is what I am using right now.

`trimmedRows: { 0: true, 1: false, 2:false }`

It is assigned as a Prop but no row gets hidden.

[CodeSandbox](https://codesandbox.io/s/great-borg-mpq0t?file=/src/App.vue).

Any help will be appreciated.

**Comment by revolist** [comment]
Hello @leyenda , try it now, should be working fine.
