### ISSUE TITLE
Angular installation issue

### ISSUE THREAD

**Issue by MaximeKoitsalu** [revolist/revogrid#166]
Hi,

What you have built looks really good and promising!
I was trying to quickly add the component to my angular repository, strictly following the instructions on [this page](https://revolist.github.io/revogrid/guide/framework.angular.overview.html). I install with `npm i @revolist/angular-datagrid --save`. Then in my app.module.ts I had `defineCustomElements();` and add RevoGrid to declarations array.

after that I add revo-grid component to my component.html file with columns and rows defined in the component.ts file.

But without any success.

In my terminal it says `Cannot find module '@stencil/store' or its corresponding type declarations.`

Do you have any idea how I might solve this issue?

I'm using Angular 10.

```
ERROR in ./node_modules/@revolist/angular-datagrid/dist/revogrid.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\maxime.koitsalu\WebstormProjects\jfs-frontend\node_modules\@revolist\angular-datagrid\dist\revogrid.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via
 the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author a
nd ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

![image](https://user-images.githubusercontent.com/8655862/107046261-ba32a980-67c6-11eb-93b1-c30680a1c30d.png)

**Comment by revolist** [comment]
Hello @MaximeKoitsalu, 
Thank you for reaching out here.

This is a fully independent environment build with angular.
[condesndbox](https://codesandbox.io/s/angular-datagrid-overview-d5i0b?file=/src/main.ts)

What I can see from your log you are parsing node_modules together with your source files. This is an internal dependency link where it's failing, 'coz of you don't need this library, we'll upgrade it in the future.

I would suggest to avoid external libraries type check. In your tsconfig.json:

`{
  "compilerOptions": {
    // anything here
   skipLibCheck: true // optional, extra protection
  },
  "exclude": [
    "node_modules"
  ]
}`

**Comment by MaximeKoitsalu** [comment]
Hey thanks for the answer. It partially solved my issue. Adding `skipLibCheck: true` to my compilerOptions object removed the errors referring to stencil/store. I then still had the error about "\node_modules\@revolist\angular-datagrid\dist\revogrid.ts is missing from the TypeScript compilation". I solved it by adding the above path to my tsconfig.app.json:

`  "include": [
    "src/**/*.d.ts",
    "node_modules/@revolist/angular-datagrid/dist/**/*.ts"
  ],`
