### ISSUE TITLE
Could this gird implements have "sparklines" in cell?

### ISSUE THREAD

**Issue by Slach** [revolist/revogrid#171]
Hello, thanks a lot for your efforts
great project

Could this gird implements have "sparklines" in cell?

**Comment by revolist** [comment]
Hello, could you please provide sample what are sparklines for you?

**Comment by Slach** [comment]
https://pmmdemo.percona.com/graph/d/pmm-qan/pmm-query-analytics
![image](https://user-images.githubusercontent.com/105560/107877670-b3571580-6eef-11eb-9818-4b1a77d7330a.png)

**Comment by revolist** [comment]
Got it, 

@Slach, and what is your actual questions?
Are you asking can you render sparklines inside of the grid? If so you can do this for sure in any way you like.
If question does we provide a sparkline plugin then the answer is not yet, we aren't working on anything like this yet, may be in the future.

**Comment by Slach** [comment]
thanks a lot for information

**Comment by revolist** [comment]
@Slach you are always welcome.
