### ISSUE TITLE
Hints on rendereing cells

### ISSUE THREAD

**Issue by bossevn** [revolist/revogrid#172]
Hi

environment: 
	React 16.14.0 / TypeScript
	"@revolist/revogrid": "^2.9.3",
	"@revolist/revogrid-react": "^2.9.2",	

First of all, congratulations for RevoGrid. It's really amazing.

I'm working on a students's grades sheet project and I need to display cells in diferent color acordding to the grade value in a certain column.

Because of the complexity of the process, I work with source of string[][] and an underling mirror structure of grade definitions. The same occurs for columns.

The code below works fine for setting up de cell value:

```
columns={gridCols}
source={sheet}

onAfterEdit={({ detail }) => {
          const d = detail as Edition.BeforeSaveDataDetails;
          const nCol = Number(d.prop);
          const gradeValues = setGradeValues(
            d.val || "",
            gradeData[d.rowIndex][nCol],
            gradeCols[nCol]
          );
          gradeData[d.rowIndex][nCol] = gradeValues;
          const row = sheet[d.rowIndex];
          row[nCol] = gradeValues.displayValue;
        }}

```
"setGradeValues" is a complex process wich normalize the value according to business roles contained in gradeCols.
 
My problem is that I cant pass grade's properties to RevoTypes.PropertiesFunc, maybe because of limitations of React or mine.

It would be nice if we have an "onGetCellStyle" event or if Edition.BeforeSaveDataDetails could have a "styles" field to override the style applied to a cell.

I'm not that fluent in React or other web frameworks, so I would appreciate any hint.

Thanks, Eduardo

**Comment by bossevn** [comment]
Got it!

A little trcky, but works!

```
...
const [colors] = useState(new Map<string, string>());
...
onAfterEdit={({ detail }) => {
          const d = detail as Edition.BeforeSaveDataDetails;
          const nCol = Number(d.prop);
          const gradeValues = setGradeValues(
            d.val || "",
            gradeData[d.rowIndex][nCol],
            gradeCols[nCol]
          );
          gradeData[d.rowIndex][nCol] = gradeValues;
          const row = sheet[d.rowIndex];
          ***> colors.set(`${nCol}-${d.rowIndex}`, gradeValues.color);
          row[nCol] = gradeValues.displayValue;
        }}
...
const gradeStyles = useCallback(
    (props: RevoTypes.ColumnDataSchemaModel): RevoTypes.CellProps => {
      const colour =
        colors.get(`${Number(props.prop)}-${props.rowIndex}`) || "inherit";
      return {
        style: {
          // fontSize: "16px",
          backgroundColor: "inherit",
          textAlign: "right",
          color: colour,
        },
      };
    },
    [colors]
  );

```
![image](https://user-images.githubusercontent.com/848509/107892059-5e23ff80-6f01-11eb-8ff8-e17a639060f9.png)

**Comment by revolist** [comment]
@bossevn glad you've got it. Closing for now.
