### ISSUE TITLE
Refresh vue component render

### ISSUE THREAD

**Issue by Icarian2021** [revolist/revogrid#173]
Hi

When refreshing the content of a cell as described below, rendering happens instantaneously for ordinary cells.
However, when using a VGridVueTemplate as cell template, the content shown through the vue component will only refresh when leaving and entering the viewport.

Is there a way to rerender the linked vue component on demand without leaving/entering viewport?

```
this.planningRows[0]['date'] = 'test';
let grid = document.querySelector('revo-grid');
grid.source = this.planningRows;
grid.refresh('all');
```

Thanks,
Icarian

**Comment by revolist** [comment]
Hello @Icarian2021,
- For the future reference please consider create vue issues below the vue repo.
- Also provide us with a real sample of issues in code box or any other environment according to the issue template.

Based on what you are saying I think it is quite similar problem which was posted already and it was incorrect usage of template:

https://github.com/revolist/vue-datagrid/issues/4

**Comment by Icarian2021** [comment]
Hi @revolist,

Thank you for your quick response!
Oops, I overlooked the vue repo. I'll pay attention in the future.

The solution you referred to has been integrated in the code sample below.
However, the vue component is still only refreshing on scrolling up & down.

https://codesandbox.io/s/still-worker-i2jf1?file=/src/App.vue

Thank you for your help,
Icarian

**Comment by revolist** [comment]
Hello @Icarian2021,
I have tried to understand what are you referring to, but with no success.
Can you provide a simple example that represents only your problem?
