### ISSUE TITLE
Row grouping closing behavior

### ISSUE THREAD

**Issue by derekchan916** [revolist/revogrid#174]
During a scenario where you have 2 layers of grouping, if you close, it is expected that the _all_ the children will also be "trimmed", not just the first grouping child.

For example in the image below, A is the parent group and 0, 2, 15, 30, etc are the children group. However, clicking on "A" will only "trim" group 0, instead of _all_ the children. 

![image](https://user-images.githubusercontent.com/12720511/108815948-45e26d80-75f0-11eb-9f55-5af217edc53d.png)

**Comment by revolist** [comment]
Hello @derekchan916, thank you for posting the issue, it's inside of the group plugin expand service.
We'll look at it later this week. 
If you need it asap you can always collaborate. 

Appreciate your post on it.

**Comment by Alexander-Trinh** [comment]
Here is my reproduction of this error:
https://codesandbox.io/s/select-all-forked-83nni?file=/src/App.vue
So basically if you close the level 1 group the level 2 do not dissapear except the first value.

**Comment by c4b4d4** [comment]
I'm experiencing the same problem. Is there any interest on fixing this issue?

**Comment by c4b4d4** [comment]
This has been solved in the latest version of the library, just confirmed it. @Alexander-Trinh @derekchan916
