### ISSUE TITLE
Small issue with scrolling with a very small number rows

### ISSUE THREAD

**Issue by derekchan916** [revolist/revogrid#178]
Hey! Here's a minor issue with scrolling. If you have a table with only 2 rows, or simply just a small number of rows, you can use the mouse wheel to scroll and the data will disappear for a split second. Of course it depends on how vigorously you scroll and how many rows you have, so it is my guess that there is something happening on the `mousewheel` event. In the video below, I have removed all the row and column groupings and diminished the number of rows to 2. 

Let me know if this is in your roadmap! If not, feel free to point me in the right direction to fix it in the "revogrid" way and I can put up a PR. 

BTW it can happen with columns too, but it's harder to repro with columns. 

https://user-images.githubusercontent.com/12720511/108961465-5b1fd080-76b2-11eb-9902-0bbff60d421f.mov

**Comment by revolist** [comment]
@derekchan916 thank you for this issue. Will look into it asap.

**Comment by revolist** [comment]
@derekchan916 fixed in the latest release
