### ISSUE TITLE
Column select for vanilla java script

### ISSUE THREAD

**Issue by mahmoodnasr** [revolist/revogrid#181]
Hi,
is column select for vanilla javascript supported ?

**Comment by revolist** [comment]
Hello @mahmoodnasr 
I don't fully understand your request... currently column select is not implemented at all.

There is a feature in our roadmap for it.

What I can suggest if you really need it fast we could extend grid api for external selection and you would be able to select range programatically. You already have access to column click. This would solve your problem.

But to make fully production solution would take sometime for us, considering our overload at this moment.

**Comment by revolist** [comment]
Or did you talk about column drop down select?

**Comment by mahmoodnasr** [comment]
Thank you for quick reponding . Yes drop down select what i mean.

**Comment by revolist** [comment]
Hello @mahmoodnasr 
You can find it here, created template for you.
Template based on pure static HTML:

https://codesandbox.io/s/revogrid-staticjs-column-jvztc?file=/index.html
