### ISSUE TITLE
Bug when revo-grid is removed from DOM

### ISSUE THREAD

**Issue by lauri865** [revolist/revogrid#188]
Error: Uncaught TypeError: Cannot convert undefined or null to object 

<img width="732" alt="Screenshot 2021-03-05 at 12 38 51" src="https://user-images.githubusercontent.com/3652743/110110906-cb63db80-7daf-11eb-94d7-048c353cb58d.png">

**To Reproduce**
https://codesandbox.io/s/revogrid-svelte-forked-wooqz (click on hide/show and check the console)

**Comment by lauri865** [comment]
Seems like it was introduced in v2.9.7 first

**Comment by revolist** [comment]
@lauri865 that is right

https://github.com/revolist/revogrid/releases/tag/v2.8.0
Has this fix included, will update svelte soon.
