### ISSUE TITLE
The table data is not displayed correctly when used with keep-alive

### ISSUE THREAD

**Issue by wuchuanxun** [revolist/revogrid#190]
Step 1: open [CodeSandBox](https://codesandbox.io/s/revo-infinity-list-forked-815jo?file=/src/main.js) in new Tab
Step 2: change menu to "B"
Step 3: change menu back to "A"
Step 4: scroll table, you will find that the data is not displayed

**Comment by revolist** [comment]
Old issue, can not reproduce
