### ISSUE TITLE
Get active (focused) cell / row

### ISSUE THREAD

**Issue by lauri865** [revolist/revogrid#191]
Is there a way to get an active or focused cell or row (data)?
Want to implement custom keyboard shortcuts when e.g. enter is pressed on a cell, but didn't find any APIs to pull it off.

**Comment by revolist** [comment]
Hello @lauri865, I would suggest tracking the focus event, you can get it with the beforeCellFocus event.

**Comment by lauri865** [comment]
Thanks! I started with that, the only problem with that tho is that there’s no way to jniw when the focus is lost/cleared.

**Comment by revolist** [comment]
Hello @lauri865, yes, we avoid passing extra data in events and we pass only needed minimal amount of data for props.
According to focus lost event this makes sense.
I suggest we add it here:
https://github.com/revolist/revogrid/issues/62#issuecomment-790652994

**Comment by a5601564** [comment]
it is any way to get focus for a cell?

**Comment by revolist** [comment]
@a5601564 there are several options you can go with:
- track focus change with event beforecellfocus
- use async method getFocused()

You can read more in https://revolist.github.io/revogrid/guide/api.html
