### ISSUE TITLE
beforeCellFocus missing prop when moving between pinned/non-pinned column with arrow keys

### ISSUE THREAD

**Issue by lauri865** [revolist/revogrid#192]
beforeCellFocus missing prop when moving between pinned/non-pinned column with arrow keys. Made a quick reproduction down below.

**To Reproduce**
https://codesandbox.io/s/revo-grid-vanilla-js-forked-h0xxv

Take the focus to the grid and use arrow keys to move between "first" and "second column" and check the console.

**Comment by revolist** [comment]
fixed
