### ISSUE TITLE
RevoGrid Documentation Enhancement

### ISSUE THREAD

**Issue by stevexm** [revolist/revogrid#193]
Hi: just started using RevoGrid for a project, and I have to add my voice that it is truly wonderful. Building it with StencilJS was a very smart strategy!

I am moving beyond basic Grid configuration and spending a lot of time re-reading api docs as well as reviewing the Codesandbox examples. _What I would really would like, is to be able to view the main demo source code on the RevoGrid website: https://revolist.github.io/revogrid/demo/ ._ That way, I can quickly scan the working source for the feature I am trying to implement and get my version running faster.

Can I suggest an enhancement for the RevoGrid documentation, if available, is to post the main demo source and/or a link to it?

Thank you again for a great tool and making it open source.

Warm regards from Australia,

Steve

**Comment by revolist** [comment]
Hello @stevexm,
We really appreciate so positive feedback on our project.

Sorry, I didn't get your request. Would you like to get a demo source code? It is available just not on codebox but as a part of GitHub project: https://github.com/revolist/revogrid-vuepress/blob/main/src/.vuepress/components/demo-page.vue

Or are you asking about something else for a demo?
It's very important for us to provide you quick jump in our API, any suggestions are very welcome.

Thank you!

**Comment by stevexm** [comment]
Wow, you guys are really fast ... thank you!

Looking at the code from the demo-page.vue link and I am getting a better idea of how to handle the grid configuration. I really appreciate your helping me out. Next task for me is to figure out how best to handle column reordering via drag-and-drop (sortablejs).


I will certainly post documentation suggestions and related for the community to have. Is the issues list the best place to do so, or would you like a fork/branch of the project and PRs to be submitted?

Thanks again,

Steve

**Comment by revolist** [comment]
Hello @stevexm, PRs are preferable
Thank you.
