### ISSUE TITLE
Row headers not working with bootstrap-vue

### ISSUE THREAD

**Issue by Magenta94** [revolist/revogrid#194]
**Describe the issue**
With `:row-headers="true"` you can see that row headers are active but the labels on it are not visible. The problem is probably a conflict with boostrap.css.

**To Reproduce**
Check here https://codesandbox.io/s/quirky-dan-ruyv0?file=/src/App.vue
Try to remove line 16: `import "bootstrap/dist/css/bootstrap.css";`
You should see the labels appearing when deleting the import, but it should not conflict with bootstrap css.

**Comment by revolist** [comment]
Hello @Magenta94 
Thank you for posting it here.
Boostrap providing global .col, .row classes which are conflicting with existing grid version.

There is a plan to make our classes more complex in next version.

**Comment by Magenta94** [comment]
Thanks, I'll wait for it.

**Comment by revolist** [comment]
@Magenta94,
fixed in 3.0.0-beta.1
your sample updated:
https://codesandbox.io/s/infallible-surf-d9g1p?file=/src/App.vue

be aware 3.0 has style change and all events had been changed as well to lowercase.

**Comment by Magenta94** [comment]
Hi, I think that something else is not working with bootstrap-vue. With revolist version 3.0.2 when you click something you get
**TypeError Cannot read property 'clearAll' of undefined**
check it here https://codesandbox.io/s/cocky-wright-xivcl?file=/src/App.vue

**Comment by revolist** [comment]
@Magenta94 was updated in 3.0.3, ty for the catch!
problem with build, sorry :-)
