### ISSUE TITLE
Editable column headers

### ISSUE THREAD

**Issue by Magenta94** [revolist/revogrid#195]
Hi it's me again :D 
Is it possible to implement editable column headers? For example if sorting is disabled, a double click on a cell header makes it editable like a normal cell.

I'd like to contribute but unfortunately I don't know typescript.

**Comment by revolist** [comment]
Hello @Magenta94, 
We don't plan this feature for now.
But there is a way to achieve what you are talking about. There are some ideas I can suggest to you:
1) You can switch your template of headers based on some parameter inside of column and control grid externally
2) Second solution is more suggested for you. I suggest to hide existing headers and use pinnedTopSource, this will provide you with a [fixed header](https://revolist.github.io/revogrid/guide/rows.pinned.html) and keep editable functionality, just hide existing header with css and you are good to go
