### ISSUE TITLE
Troubles in router spa with export.plugin.ts

### ISSUE THREAD

**Issue by leyenda** [revolist/revogrid#196]
Good day everyone,

The export plugin embeds an "a" tag to the dom and then click it to download the file.
It works really well but it got handle by the router of my spa and end up in an 404 route.

I dont know if this is too particular to the router we use but it can exclude such links with a custom class "external".

> _export.plugin.ts line 45_

```js
    a.style.display = 'none';
    a.setAttribute('href', url);
    // a.classList.add('external');
    a.setAttribute('download', name);
    this.revogrid.appendChild(a);
    a.dispatchEvent(new MouseEvent('click'));
    this.revogrid.removeChild(a);
```

How we could handle this and at the same time keep it to be a generic solution. Maybe adding and option for the plugin to add custom classes to the link?

I can code the solution, just wanted to discuss first to be open to your ideas.

**Comment by revolist** [comment]
Hello @leyenda 
yes, if you want you can apply custom classes as an extra option for the plugin. 
Or you can extend plugin and use it on your own, the downside of this solution is you'll not be able to update easily
