### ISSUE TITLE
How to disable single row or cell

### ISSUE THREAD

**Issue by Magenta94** [revolist/revogrid#199]
**Describe the issue**
Hi, let's say that I have a table like this https://codesandbox.io/s/vigorous-edison-2j3il?file=/src/App.vue so the user can edit the header. Somethimes I want the header (first row) readonly, I know I can disable a single column with `readonly: true`, but is it possible also on a specific row?

Also the first cell of the first row (the empty one) in this case should be always readonly. Is is possible to make readonly a specific cell?

Thanks

**Comment by revolist** [comment]
Hello @Magenta94 
https://codesandbox.io/s/serene-knuth-y38gd?file=/src/App.vue
check this sample (copy of yours), there is sample, will add it soon to main doc.
Don't forget to update to the latest version, in 3.0.2 was small issue in build on focus error.
