### ISSUE TITLE
Paste content with more rows / cols

### ISSUE THREAD

**Issue by mayous83** [revolist/revogrid#203]
I'm trying to paste from excel a content that has more rows and columns than the one present in the component but the grid doesn't get the right dimensions

Reproduce issue:
using the default demo:
https://codesandbox.io/s/vue-3wkzi?from-embed

paste a content from excel file that has more rows / cols

**Comment by revolist** [comment]
Hello @mayous83, thank you for this update, currently, Copy/Paste functionality is limited by visible area. We are going to improve this feature with time.

There are several options you can do right now:
- Best way: add events to `revogr-clipboard.tsx` and provide us with Pull Request (this will be supported then in farther versions, we shall add these events in the future anyway but now we overloaded with other features). With event you can extend existing data-source and prevent original paste.
- Or fork, then make an extension of the existing copy/paste plugin and make it increasing data source with new rows;
- Or on document paste just extend your original data source with the number of rows you are pasting in.
