### ISSUE TITLE
Multiple Drag and Drop

### ISSUE THREAD

**Issue by sarahschau** [revolist/revogrid#204]
Hello, 

on the demo page you included the drag and drop for rows. I wanted to know if it's possible to add multiple drag and drop (e.g. select rows and then drag them). 
I can't find anything about the drag and drop in your docu.

Thanks for your help.
Ps. very nice project!

**Comment by revolist** [comment]
Hello @sarahschau, thank you for using our grid.
It is not supported out of the box but you can easily make it by yourself. All you have to do just remember rows you want to drag and on drop event upgrade collection with all rows you want.

**Comment by lionsarmor** [comment]
I am having a problem triggering an event on drag to do this, I just want to get the output of the event, and a way to update the collection, any help would be appreciated
