### ISSUE TITLE
Column select bug with numerical index

### ISSUE THREAD

**Issue by HtheChemist** [revolist/revogrid#205]
I am opening an issue here since this repo seems to be more active/monitored.

There is a bug when using numerical index with the column select plugins thats stop it from working: https://github.com/revolist/revogrid-column-select/issues/3

I have made a very simple pull request to solve it if anyone has the same problem: https://github.com/revolist/revogrid-column-select/pull/4

**Comment by revolist** [comment]
Fixed in v4
