### ISSUE TITLE
Canceling the default behavior for the Enter key

### ISSUE THREAD

**Issue by whatifoff** [revolist/revogrid#206]
Now, when you first press Enter, it becomes possible to edit the contents of the cell.
Pressing Enter again moves to the next line.
How can I reverse this behavior? If you want the focus to remain on the current line when you press Enter again

**Comment by revolist** [comment]
Check revogr-edit.tsx and text-editor.tsx
There is export type SaveCallback = (value: SaveData, preventFocus: boolean) => void;

preventFocus is what you were looking
