### ISSUE TITLE
How to get sorted/filtered data after sorting and filtering

### ISSUE THREAD

**Issue by navinsaini** [revolist/revogrid#207]
Is there any way to get the sorted data and filtered data after sorting and filtering applied?

**Comment by van-huyen** [comment]
+1 need help

**Comment by navinsaini** [comment]
@van-huyen  I am getting the sorted data like this in Angular
`let sortedData = await this.revoGrid.getVisibleSource();`

**Comment by van-huyen** [comment]
> @van-huyen I am getting the sorted data like this in Angular
> `let sortedData = await this.revoGrid.getVisibleSource();`

Oh, i can see it
Thanks @navinsaini
