### ISSUE TITLE
Can't figure out how to add tooltip

### ISSUE THREAD

**Issue by akramgassem** [revolist/revogrid#211]
I'm using revo grid for several grids in my own project and can't figure out how to build a tooltip with my custom cell template 

In fact I'm using vue bootstrap as library for components. And I try to mix h function with the tooltip from vue bootstrap. But it renders undefined. 

Please can anyone help me to achieve this feature. 

Thank you for this great revolutionary grid.

**Comment by revolist** [comment]
Hello @akramgassem,
problem you described here is you don't have reference to main vue application inside of cells.

If I simplify things without going into details:

- You have grid component, it is totally isolated system
- You have cells, it's also isolated peaces of code
- You need to pass your vue app inside of cells and render it as vue component as part of main application where vue system applied, only then you'll be able to make what you are looking for. 

There is another option to apply tooltips based on parent, when you convert regular tooltip even for new elements to new visualisation.
