### ISSUE TITLE
How to hide columns?

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#214]
Hi @revolist ,

How to hide a column on revo grid?
I tried set column size = -1 and style: display none, but "column header" will display when i switch to responsive mode.

        {
          prop: 'hide',
          name: 'Hide',
          size: -1,
          cellProperties: ({ prop, model, data, column }) => {
            return {
              style: {
                display: 'none',
              },
            }
          }
        },

hope you guide me
Thanks

**Comment by revolist** [comment]
Hello @van-huyen 
the best way would be to keep 2 collections on your side, 1st for grid 2nd for all data, and update 1st collection with visible rows only.
