### ISSUE TITLE
Lost focus of Filter input box

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#215]
Hi @revolist 

When using Filter, input the value,
![image](https://user-images.githubusercontent.com/83264685/119089168-af81e480-ba44-11eb-88a3-2afb59f1a0d3.png)

And lost focus in filter input box and switch to focus grid
![image](https://user-images.githubusercontent.com/83264685/119089446-1a332000-ba45-11eb-9972-d5e34b9151a1.png)

Hope you fix it soon,
Thanks,

**Comment by revolist** [comment]
@van-huyen done

**Comment by van-huyen** [comment]
Hi @revolist ,
I have tried update new version (3.0.97) with command npm i @revolist/revogrid --save;
, but it still not working. Do i upgrade wrong way?

![image](https://user-images.githubusercontent.com/83264685/126925909-4d2f526a-83e0-4db9-a846-74ef4e15c754.png)
