### ISSUE TITLE
[Feature Request] stretch like table display

### ISSUE THREAD

**Issue by odex21** [revolist/revogrid#220]
My project needs to make each column expand evenly. Just like element-plus's table
I tried it myself, because I use vue, so I wrapped a component and listened to the change of columns to calculate the size of the columns that are not set to size, while in the resize event, through the plugin to get the dimensionProvider to update the size of columns.
But the current plugin interface does not provide dimensionProvider, so I used patch-package to modify the source code.
I think it might be possible to enhance the current stretchPlugin or change the plugin's interface.

**Comment by odex21** [comment]
Here is some code I'm currently using

```ts
import { clone } from 'ramda'
import { Components } from '@revolist/revogrid'
import { RevoGrid } from '@revolist/revogrid/dist/types/interfaces'

export const createColumns = (
  size: number,
  cols: Components.RevoGrid['columns']
) => {
  let _size = size
  const autoColMap = new Set<RevoGrid.ColumnRegular>()

  // get the width left
  const init = (arr: RevoGrid.ColumnDataSchema[]) => {
    arr.forEach((c) => {
      if (assertColumnGrouping(c)) {
        init(c.children)
      } else {
        if (c.size) {
          _size -= c.size
        } else {
          autoColMap.add(c)
        }
      }
    })
  }

  // I did not carefully test vue's responsive data and stencil's immutable
  // data, so I directly deep cloned a copy, because the columns are
  // generally not a lot, so there is no problem for now.
  const res = clone(cols)
  init(res)

  if (_size > 0) {
    let avgSize = Math.floor(_size / autoColMap.size)

    // first deal with the columns with minSize
    autoColMap.forEach((e) => {
      if (e.minSize && e.minSize > avgSize) {
        _size -= e.minSize
        e.size = e.minSize
        autoColMap.delete(e)
      }
    })

    //update avgSize
    avgSize = Math.floor(_size / autoColMap.size)

    autoColMap.forEach((col) => {
      col.size = Math.max(avgSize, 100)
      _size -= col.size
    })
  } else {
    // if there is no width left to assign
    autoColMap.forEach((col) => {
      col.size = col.minSize ?? 100
    })
  }

  return res
}

function assertColumnGrouping(
  c: RevoGrid.ColumnDataSchema
): c is RevoGrid.ColumnGrouping {
  return !!c.children
}

```


and here is the plugin
```ts
class StretchPlus extends BasePlugin {
  resizeObserver: ResizeObserver

  constructor(
    revogrid: HTMLRevoGridElement,
    private provider: {
      dimensionProvider: DimensionProvider
      columnProvider: ColumnDataProvider
    }
  ) {
    super(revogrid)

    this.resizeObserver = new ResizeObserver(() => {
      const type: RevoGrid.DimensionCols = 'rgCol'
      console.log('update cols resizeObserver')

      this.revogrid.columns = createColumns(
        this.revogrid.offsetWidth - 17,
        props.columns
      )

      const sizesArr = this.provider.columnProvider
        .getColumns('rgCol')
        .map((e, i) => [i, e.size])
        .filter((e) => e[1])
      const sizes = Object.fromEntries(sizesArr)

      this.provider.dimensionProvider.setDimensionSize(type, sizes)
      this.provider.dimensionProvider.setRealSize(sizesArr.length, type)
    })

    this.resizeObserver.observe(this.revogrid.parentElement!)
  }

  destroy() {
    this.resizeObserver.disconnect()
  }
}

```

This class is written in Vue's components, in order to get the columns in the props.

I think there should be a better way to achieve this effect. If you can give a little hint, I can submit a PR.

**Comment by revolist** [comment]
Hello @odex21, there is a way, actually, we've started to create some plugins for this inside of our own products.
I suggest looking into code stretchPlugin.ts and create your own plugin based on ideas from there.

**Comment by revolist** [comment]
@odex21 https://github.com/revolist/revogrid/projects/1#card-65528130

**Comment by franz-josef-kaiser** [comment]
@revolist your link now leads to an empty board :)

**Comment by shayneoneill** [comment]
Any updates on this?

**Comment by m2a2x** [comment]
There was a Pro version plugin where column is getting stretched by index, 'all' or 'last'

**Comment by Karan9615-off** [comment]
@m2a2x How can we make RevoGrid columns responsive to screen size?

**Comment by Karan9615-off** [comment]
> @m2a2x @revolist How can we make RevoGrid columns responsive to screen size?

Any Update ??

**Comment by m2a2x** [comment]
Here's a response you could use:

---

Hi @Karan9615-off,

I understand that you're eager to get support on your feature request, but please note that open-source projects, like RevoGrid, often rely on the contributions of volunteers and a community-driven approach. This means that immediate support, especially within a 6-hour window, is not typically possible.

For urgent requirements or feature requests, we recommend considering our Pro version, which offers prioritized support and additional features. If you're interested, we can discuss how to transition to the Pro version and ensure your needs are met promptly. We have this feature as part of the pro version. By default you have a way to stretch last column only.

Thank you for your understanding and patience!
