### ISSUE TITLE
How to use grid methods like updateColumns in Vue.js ? 

### ISSUE THREAD

**Issue by Kalo0m** [revolist/revogrid#222]

**Comment by bbbford** [comment]
I also am confused about how to use the methods. I would like to programmatically change the sorting of the grid.

**Comment by van-huyen** [comment]
did you mean using function like this?

var viewData = await this.$refs.vgrid.$el.getVisibleSource()

this.$refs.vgrid.$el.refresh('all')

this.$refs.vgrid.$el.scrollToRow(_rowIndex)

https://revolist.github.io/revogrid/guide/api.html#methods

**Comment by bbbford** [comment]
Exactly! thanks @van-huyen

**Comment by Yiidiir** [comment]
This doesn't work in Vue 3

**Comment by paramula** [comment]
![resim](https://user-images.githubusercontent.com/4445339/220558201-7fac2761-410c-4c40-9fc5-90c64d5bf2af.png)

hidding rows after use this.$refs.vgrid.$el.scrollToRow(_rowIndex) . is there fix

**Comment by Yiidiir** [comment]
@Kalo0m @revolist Why close this unresolved issue?
What did you end up doing  @Kalo0m ?

**Comment by Kalo0m** [comment]
Oh sorry, I didn't see the last message!

**Comment by ToniMHeinonen** [comment]
> This doesn't work in Vue 3

It does work in Vue 3 with script setup, but you just have to use the new ref system: https://vuejs.org/guide/essentials/template-refs.html it took me ages to figure this out.

Here is a small example:
```
<script setup lang="ts">
const gridRef = ref(null)

onMounted(async () => {
  // Add small delay, otherwise value seems to be null
  await new Promise((resolve) => setTimeout(resolve, 10))
  if (gridRef.value) {
    const grid = gridRef.value as any
    const source = await grid.$el.getVisibleSource()
    console.log('source', source)
  }
})
</script>
```
And then just add ref="gridRef" to you VGrid component in template. I just wish that I would find a proper way to make this work correctly with TypeScript, at the moment I need to use the any type...
