### ISSUE TITLE
Grouping by prop does not allow custom template

### ISSUE THREAD

**Issue by yumi-aiassets** [revolist/revogrid#223]
I want to add a select box to the grouping prop header so that I can select all the rows in that particular group only. I can't seem to find a way to achieve this yet.

**Comment by revolist** [comment]
For now grouping experimental feature. If you want to get custom data there are 2 ways:
- You can copy plugin and extend it on your own.
- You can collaborate and extend our template with custom template props, it'll provide you support in the future.
