### ISSUE TITLE
VanillaJs multiply html element in cell

### ISSUE THREAD

**Issue by lotarbo** [revolist/revogrid#226]
Hello, i wanna use smt like `<p>Checked</p><p>11-02-2021</p>` in cell.
I used **cellTemplate** like
```
cellTemplate: (createElement, props) => {
            let data = props.model[props.prop];
            return createElement('p', {}, data.check);
},
```

but i dont uderstand how i can create second P tag with data.updated_at
ps data is object with name and updated_at
Thanks

**Comment by revolist** [comment]
Hello,

here you can find example of complicated dom tree:
https://revolist.github.io/revogrid/guide/jsx.template.html

But if you can I suggest to use jsx/tsx
