### ISSUE TITLE
Is date select supported in Vanilla Javascript?

### ISSUE THREAD

**Issue by schnetzlerjoe** [revolist/revogrid#227]
I cant seem to get the date select to work utilizing vanilla javascript through https://www.jsdelivr.com/package/npm/@revolist/revogrid-column-date. How would I get a date selector to work via browser/javascript? Thanks!

**Comment by revolist** [comment]
Hello @schnetzlerjoe 

https://codesandbox.io/embed/revo-grid-vanilla-date-js-i7fhi?fontsize=14&hidenavigation=1&theme=dark
probably is what you are looking for
