### ISSUE TITLE
How add custom props or emit in VGridVueTemplate?

### ISSUE THREAD

**Issue by Nikitoring** [revolist/revogrid#230]
I need to use custom component in my cellTemplate with my props and emits. How can I pass props in VGridVueTemplate?
Or I can use JSX render?

**Comment by Nikitoring** [comment]
I created PR [#26](https://github.com/revolist/vue-datagrid/pull/26)

**Comment by van-huyen** [comment]
Hi @Nikitoring 

I'm using JSX render for creating custom cell with button(open dialog, take action...) like this:

![image](https://user-images.githubusercontent.com/83264685/126096220-1fb1ae1a-3c76-4cb3-97ff-9c69bc101ba3.png)

You can creat any thing in the cell with JSX  ^^

Regard!

**Comment by Nikitoring** [comment]
@van-huyen But it's not true way for my project. Because I use cell component like vue component. My example https://codesandbox.io/s/revogrid-vuecomponent-forked-xbfpv?file=/src/App.vue shows how I want to use component with my props. And I can't  do it inside jsx. May be you have an idea how to do it without my PR?

**Comment by van-huyen** [comment]
@Nikitoring 
i was understand your requirement,
i has tried but not completed.
i will try create and use it as soon as possible

Regard!

**Comment by van-huyen** [comment]
With component
![image](https://user-images.githubusercontent.com/83264685/127104564-0fe22211-ade8-43b1-ae97-ed62cf745de3.png)


I have tried using JSX render like this:
![image](https://user-images.githubusercontent.com/83264685/127104015-4c9b8788-1cba-4a2d-9ee4-f19abfd8dec3.png)

And result like:
![image](https://user-images.githubusercontent.com/83264685/127104133-6073c35f-1718-4327-a4eb-fbacfedb53b5.png)

If use column's prop, result like:
![image](https://user-images.githubusercontent.com/83264685/127104401-547450e4-f28e-4681-a9aa-784f80cd623a.png)


![image](https://user-images.githubusercontent.com/83264685/127104358-9cbe3170-ad63-4b8d-97c5-6a4c4939058e.png)

Regard!

**Comment by donmb1** [comment]
#

**Comment by marcos-vinicius-dev** [comment]
I am also interested in this

**Comment by lucasgarciabertaina** [comment]
It's possible to pass props inside a custom VGridVueTemplate?

**Comment by donmb1** [comment]
I found some kind of workaround:

In the parent component:
```
import MyComponent from 'MyComponent.vue'

const payload = { something: 'foo' }

const columns = [
...
{ name: '', cellTemplate: VGridVueTemplate(MyComponent), size: 100, autoSize: true, prop: payload }
...
]
```
In MyComponent.vue we have access to all default props of a row, like so:
```
export default defineComponent({
  props: ['model', 'prop'],
  ....
})
```

A custom prop does not work. You have to use existing props like `model` or `prop`. Within `model` you will find all attributes of your model.

Hope that helps anyone.

**Comment by artoriasless** [comment]
ad default,pass column config like the following
```typescript
  {
      prop: 'columnAction',
      label: '',
      size: 75,
      minSize: 75,
      maxSize: 75,
      readonly: () => true,
      cellTemplate: VGridVueTemplate(EditableGridCellColumnAction),
    }
```

if you need pass custom props or emits,try the following
```typescript
  {
      prop: 'columnAction',
      label: '',
      size: 75,
      minSize: 75,
      maxSize: 75,
      readonly: () => true,
      // 对应单元格的渲染模板
      cellTemplate: VGridVueTemplate(
        h(EditableGridCellColumnAction, {
          onDeleteRow: payload => {
            console.info(payload);
          },
        })
      ),
    }
```

**Comment by faridsafwan** [comment]
Hi @artoriasless, I receive this error --> ReferenceError: h is not defined. and how you trigger/emits the function from editor?

**Comment by artoriasless** [comment]
> Hi @artoriasless, I receive this error --> ReferenceError: h is not defined. and how you trigger/emits the function from editor?

```
import { h } from 'vue';
```

`h` comes from `Vue`

**Comment by JakobMiksch** [comment]
> I found some kind of workaround:
> 
> In the parent component:
> 
> ```
> import MyComponent from 'MyComponent.vue'
> 
> const payload = { something: 'foo' }
> 
> const columns = [
> ...
> { name: '', cellTemplate: VGridVueTemplate(MyComponent), size: 100, autoSize: true, prop: payload }
> ...
> ]
> ```
> 
> In MyComponent.vue we have access to all default props of a row, like so:
> 
> ```
> export default defineComponent({
>   props: ['model', 'prop'],
>   ....
> })
> ```
> 
> A custom prop does not work. You have to use existing props like `model` or `prop`. Within `model` you will find all attributes of your model.
> 
> Hope that helps anyone.

This worked for me. Thanks @donmb1 🥇

**Comment by os-tohe** [comment]
I was able to make it work by using createVNode from vue library:
```
// TableCell is the custom Vue component
const cellTemplate = VGridVueTemplate(
  createVNode(TableCell, {
    // Any prop you want
    value: 'value',
  })
)
```
And then just receive the prop in your Vue component:
```
defineProps({
  value: {
    type: String,
    required: true,
  },
})
```

**Comment by JakobMiksch** [comment]
> The example provided by [artoriasless](https://github.com/revolist/revogrid/issues/230#issuecomment-1484495996) did not work with TypeScript,

In my Vue3 application with Typscript I did not have any problems.

**Comment by os-tohe** [comment]
> In my Vue3 application with Typscript I did not have any problems.

Strange, I get this error if I use the `h` from `vue` library:
```
No overload matches this call.
The last overload gave the following error.ts(2769)
runtime-core.d.ts(1490, 25): The last overload is declared here.
```

**Comment by JakobMiksch** [comment]
okay, maybe your TypeScript settings are stricter than mine ...
