### ISSUE TITLE
New installation failed @revolist/vue3-datagrid 

### ISSUE THREAD

**Issue by ghost** [revolist/revogrid#231]
Hello everyone, I am doing a new installation, I go from Vue 2 to Vue 3 but it generates these errors

Uncaught TypeError: can't access property "emit", this.beforecolumnsset is undefined

TypeError: can't access property "registerElement", this.scrollingService is undefined

I have already installed @revolist/vue3-datagrid, but I can't find what can be wrong, I hope you can help me.

**Comment by ianoble** [comment]
Same exact thing for me too...

**Comment by wglas85** [comment]
This is a duplicate of https://github.com/revolist/vue3-datagrid/issues/5 and is supposedly fixed by our pull request https://github.com/revolist/vue3-datagrid/pull/6

**Comment by ianoble** [comment]
Any idea when that PR will be merged and released?

**Comment by wglas85** [comment]
Up to now we have no reaction from the maintainer, we'd like this one to be released, too.

**Comment by wglas85** [comment]
The PR has been merged by the maintainer and released as vue3-datagrid version 3.0.96
Please verify the fix and close this issue afterwards.
