### ISSUE TITLE
How can I merge cell in column?

### ISSUE THREAD

**Issue by Nikitoring** [revolist/revogrid#233]
I need to merge cells, like this
![image](https://user-images.githubusercontent.com/50715463/125575345-66871846-6c19-4523-9e15-e6c3ac0bd2db.png)
How can I make it?

**Comment by revolist** [comment]
@Nikitoring for not we don't provide such function,
but you can achieve it with plugin, or trick your way around with extending upper cell down

**Comment by van-huyen** [comment]
Hi @Nikitoring 

In this case, i will check value of cell in (row === row -1) and set color or border for cell that you want to hide,
It is result (long cell value will display in tooltip)

![image](https://user-images.githubusercontent.com/83264685/127285666-0b7fbda1-9c28-4cfd-bdb8-a65cd7cd1a2d.png)


Regard!

**Comment by Nikitoring** [comment]
@van-huyen but if you want edit cell you need to copy value from this cell to other merged cells?)

**Comment by van-huyen** [comment]
@Nikitoring 
Oh, i use readonly mode only, so i didn't think about that case.

In that case, you can add a prop as rank of row (hidden column), it easier for hide equal cell value foreach row.
And when edit, in afteredit (afterCellEdit) event, you can set all value by same rank of row.

Regard!

**Comment by dncdrn** [comment]
> this case, i will check value of cell in

Hi @van-huyen would you be so kind to share on how you achieve the "(long cell value will display in tooltip)" ? Thank you in advance!
