### ISSUE TITLE
How can i clear or refresh Filtered and Sorted grid

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#234]
Hi @revolist 

Sorry take your times, but how can i clear filter or sort when refresh grid.
For now, i'm using "this.$refs.vgrid.$el.refresh('all')" but it not clear filter or sort.
I have looking in document but it has clearFocus() function only.
Filter or sort will clear when i reload page (press F5) but it not good for use.

Thank and best regard!

**Comment by revolist** [comment]
@van-huyen It's a good question

added for you 2 methods:

// this is how to clear filters
window.clearFilters = function () {
        const grid = document.querySelector('revo-grid');
        grid.getPlugins().then(plugins => {
          plugins.forEach(p => {
            if (p.clearFiltering) {
              p.clearFiltering();
            }
          });

// to clear sorting
grid.clearSorting();

but keep in mind, sorting will stay until you apply new sorting, it'll not sort source back, just remove currect sorting application. to remove sorting back you should reapply source data.

**Comment by van-huyen** [comment]
Thank you for help, i have tried but it not working or i didn't know how to use :D 
Customize by your added code in my PR, it working with bellow function
![image](https://user-images.githubusercontent.com/83264685/126923671-a1088c46-0036-4544-a962-272caa1a7396.png)
