### ISSUE TITLE
Copy/Paste value into read only grid

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#238]
Hi @revolist ,

Like title, now i can paste (Ctr + v) value into cell of read only Grid, it not good to used.

I have setted useClipboard="false" for disable paste value but it disable copy value too.

How can i copy cell value with any case and 
disable paste value when read only mode.

I have referenced https://github.com/revolist/revogrid/pull/59 
and try set readonly: true for each column props, it working but not good to use ^^.
 - Can't paste value into cell but still call afterCellEdit event:
![image](https://user-images.githubusercontent.com/83264685/129666125-116e244d-b962-4bd3-a03b-f515f2e4dcf6.png)

 - And can't paste value when inputting:
![image](https://user-images.githubusercontent.com/83264685/129672968-ab737f49-cbf8-4725-8dad-7ba2bb5c030a.png)

Regards!

**Comment by revolist** [comment]
Should be fixed in 4+. Let us know if present.
