### ISSUE TITLE
Get Selected Cells/Range

### ISSUE THREAD

**Issue by ritdaw** [revolist/revogrid#239]
Firstly, great effort on the grid so far.

How can I get the selected cells in the grid? Also can I listen to when a cell/range has been selected?

**Comment by van-huyen** [comment]
Hi @ritdaw 

Now i get selected cell value by onClick, mouseDown, contextmenu... event

rowIndex = event.target.dataset.rgrow
colIndex=event.target.dataset.rgcell

var viewData = await this.$refs.vgrid.$el.getVisibleSource()
cellValue = viewData[rowIndex].colProp  // colProp: this is prop of column you want

// or dynamic columns by mouse:
var colProp= this.$refs.vgrid.columns[colIndex].prop
cellValue = viewData[rowIndex][colProp]


cell/range => I don't need this function

Regards!

**Comment by ritdaw** [comment]
Thanks.

**Comment by wglas85** [comment]
The correct way to retrieve the currently selected range is 
```
grid.selectionStoreConnector.focusedStore?.entity.store.get("range"));
```
See also pull request #263 , which adds a public function getSelectedRange() .
