### ISSUE TITLE
Dynamic templates for columns

### ISSUE THREAD

**Issue by gonzalo91** [revolist/revogrid#240]
is there a plan to have dynamic template for columns?
For example (Based on the basic vue example):
`
    <v-grid-column v-slot:['name']="{ item }"  >
      <a :href="'https://web.com/' + item.id">{{ item.id }}</a>
    </v-grid-column>
`

I already know there is the 'Cell renderer' but I think it's not enough to fulfill this need

**Comment by van-huyen** [comment]
Did you tried JSX/TSX - Custom content render ?

![image](https://user-images.githubusercontent.com/83264685/130546215-c2695847-f246-42e5-8b4a-c39e771727fc.png)

**Comment by revolist** [comment]
Closing, seems not an issue.
