### ISSUE TITLE
drag and drop it is functional?

### ISSUE THREAD

**Issue by eRendon** [revolist/revogrid#242]
how is the property to add drag and drop to table? 

In the documentation not see this but in demos its present.

Thanks.

**Comment by revolist** [comment]
Hello @eRendon ,
good catch

you can always access demo here:
https://github.com/revolist/revogrid-vuepress/blob/ca88d788f73430f802b6086b85bcbdc25049d5fd/src/.vuepress/components/demo-initial.vue

shortly you need to add draggable prop to column:

const cols = [{
		name: 'Name',
		prop: 'name',
		rowDrag: true, // can be a function
	}];

We'll add example in meantime
