### ISSUE TITLE
Problems with Shadow Dom

### ISSUE THREAD

**Issue by coelhobf** [revolist/revogrid#243]
I'm trying to use the lib inside a Web Component with shadow dom. The problem is in the event listeners, they don't catch my interactions with the table, like, click to select, or double click to edit. The double click to edit I've solved by listening to the dblclick in my component using the setCellEdit function, but the click and focus i can't solve.
If you have some ideas about what we can do to solve this problems, we'll be grateful.
My team is open to cooperate, including we would make an alternative solution to the column drag/drop issue. So, what do you think, can we cooperate?

**Comment by revolist** [comment]
Hello @coelhobf 
Sounds gr8, we are always open for cooperation

What is your problem exactly?
You are trying to catch events outside shadow Dom?

Please provide us with code http://codesandbox.io example of problem, probably I can suggest something

**Comment by coelhobf** [comment]
Hello, thanks for the reply.

The main problem is to use the <revo-grid> component inside a custom component with shadow = true on my stencil lib.
While ive been working on i couldnt focus on a cell with a click and set edit with an double click, i dont know if other features arent working too. 

I've tried to isolate the data-table component and put the code on a repository.
https://github.com/coelhobf/data-table
https://codesandbox.io/s/nervous-kilby-ltewn

**Comment by verena-ifx** [comment]
> e lib inside a Web Component with shadow dom. The pro

Any updates on this? Trying the same

**Comment by GabrielHangor** [comment]
Same...
