### ISSUE TITLE
Double full-width character (Microsoft IME-mode input)

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#244]
Hi @revolist

Sorry take your times, but how can i fix double char problem when input on Microsoft IME-mode?
Reason: when input in IME mode, it same input on "v-autocomplete" of vuejs, where dropdown list will display for user select by behavior:
1. mouse choise (mouse click event will commit the choice),        => it work normal
2. "arrow key" to move choice and "**enter key**" for commit the choice.      => issue (afteredit event called 2 times)
3. transform by "space key" and "**enter key**" for commit the choice.          => issue (afteredit event called 2 times)

I have tried backup value when first time of afteredit event and replace that in second time of afteredit event. 
It working but sometime it not working.

And after transform full-width character, i still want to input some value  (cell to edit mode) but cell was commited (not in edit mode any more).

ref: video
(you can see after enter key, grid jump by 2 rows,
in normal case, it shoud be still cell edit mode)

Thank and best regard!

https://user-images.githubusercontent.com/83264685/131074646-75e33140-9905-4a60-9e5e-02edbf7134f4.mp4

**Comment by van-huyen** [comment]
now i check this issue again and
 it has been solved, amazing!

However, after press "enter key" for choose value user want to input next text, not out cell edit mode.
I will solve by "compositionend" event (listening input on IME mode) on "afteredit" event.

compositionend: https://qiita.com/angeart/items/4ff19185fc8d7ef5fb79

Thank & best regards!

**Comment by chkaos** [comment]
@van-huyen Any update on compositionend solution ?

**Comment by van-huyen** [comment]
@chkaos 
Maybe double full-width character has been solved in latest version. 
I just add function for not out "cell edit" mode on first "enter key" press for continue typing text.
