### ISSUE TITLE
[Question] Is there any API About drag columns ?

### ISSUE THREAD

**Issue by lijie1129** [revolist/revogrid#245]
hi, everyone.

I use `revo-grid` recently, and I didn't found the API about drag columns.

so, does the newest `revo-grid` support it?

**Comment by revolist** [comment]
Hello @jarone,
sorry, such feature in work for 4.0 but not release yet.
https://github.com/revolist/revogrid/projects/1#card-54431391

**Comment by revolist** [comment]
now it's support it.
