### ISSUE TITLE
Add event listeners with JSX/TSX - Custom content render

### ISSUE THREAD

**Issue by pvter** [revolist/revogrid#246]
Hi everyone,
I'm using `revo-grid` with `Vue` and [TSX custom cell content renderer](https://revolist.github.io/revogrid/guide/jsx.template.html). I tried to add mouse and keyboard events to template elements. However react-style event listeners are not working in TSX. Is there any way to add event listeners to template elements?

**Comment by van-huyen** [comment]
Hi there,

this is my way:
![image](https://user-images.githubusercontent.com/83264685/133192454-70c2ec7c-2f70-45e3-bd4d-71ccb160e26f.png)


Regards!

**Comment by van-huyen** [comment]
Hi there,

this is my way:

![image](https://user-images.githubusercontent.com/83264685/133192726-f1a29c51-70da-4a51-ad11-895d0a69ef88.png)

hope it help you,

Regards!

**Comment by kas84** [comment]
Is there a way to do this in jsx instead of pure js?

**Comment by revolist** [comment]
Was done in v4, check sample for custom cell template
