### ISSUE TITLE
How to make cells non editable？

### ISSUE THREAD

**Issue by chneqiang** [revolist/revogrid#248]
I want to control that some cells are not editable

**Comment by van-huyen** [comment]
Hi there,

You can control any cells to disable edit mode like this:

![image](https://user-images.githubusercontent.com/83264685/133187698-d68cbd3c-d5b4-46db-a345-e974824138ad.png)

![image](https://user-images.githubusercontent.com/83264685/133186667-b94e8a3c-b4fe-4e7a-b0d2-d064c59eb5d3.png)


    // check cell you want to control by rowIndex and colName
    // Before cell edit event: beforeeditstart
    beforeeditstart(event){
    var _rowIndex = event.detail.rowIndex
    var colName = event.detail.prop
    // Example by EditFlag forEach row and colName
    // viewData: Grid source
    if(viewData[_rowIndex].EditFlag === false && colName === '// column want to control'){
        event.preventDefault()   
        return
        }
    }
        
https://revolist.github.io/revogrid/guide/api.html#events
![image](https://user-images.githubusercontent.com/83264685/133187394-35a4a378-24c7-4c13-aee7-6fa1195b3eee.png)

But it not working with copy/paste behavior. 😃 

Regards!

**Comment by Super-Chama** [comment]
@van-huyen for copy/pase behaviour use `beforeautofill`

**Comment by van-huyen** [comment]
Oh thank @Super-Chama ,

if use readonly mode, we can not control disable/enable input for each cell like this question.
i tried used beforeautofill but it not handle behavior Ctrl + V.
i'm still finding what is the event of Ctrl + V on Revo-Grid 😃 
so i'm disabling clipboard func.
![image](https://user-images.githubusercontent.com/83264685/133398034-2c207663-a67c-43e1-89cc-7501a13cd96b.png)


Regards!

**Comment by franz-josef-kaiser** [comment]
You can use the `readonly` flag. It's an `attribute` (use on VueComponent `<revo-grid readonly="true">` for all cells), as well as a `property` (use on data `source` for selected cells only).

**Comment by Jyoti-Khatkar** [comment]
@franz-josef-kaiser @Super-Chama @revolist is it possible to make a single column editable and others will be only in readOnly mode, till now i just use readOnly but it makes the whole table readOnly mode, but i want a type of attribute that works as per column.

**Comment by jorge-koki** [comment]
Lo que ise para poder realizar esto, es agregar una propiedad llamado editable, despues en el componente ejecute el evento  @beforeeditstart y luego recorro el arreglo de cuales tiene editable, y a esas le agrego  e.preventDefault();

Columns

```
{
    prop: "delete",
    name: "",
    size: 80,
    cellTemplate: VGridVueTemplate(BtnDeleteComp),
    editable: false,
  },
```

Template
```
   <VGrid
          ref="VGridRef"
          theme="material"
          style="height: 100%"
          :source="tableData"
          :columns="columns"
          :auto-size-column="false"
          :resize="true"
          :exporting="true"
          :readonly="false"
          @beforeeditstart="beforeEditStart"
        ></VGrid>

```
Function

```
function beforeEditStart(e) {
  let propsNoEditable = [];

  for (let index = 0; index < columns.length; index++) {
    if (columns[index].editable !== undefined) {
      if (columns[index].editable === false) {
        propsNoEditable.push(columns[index].prop);
      }
    }
  }

  if (propsNoEditable.includes(e.detail.prop)) {
    e.preventDefault();
  }
}
```
