### ISSUE TITLE
Column type select not working when value is number

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#249]
Hi @revolist 

Like title, when i used column select type, get source from database with:

    label: text, 
    value: number,

it is OK to add source into select box, 
but it can not select (commit value) because value is number type.

I tried convert to string type when get source from database and it working normal.
But it not good to use (convert to number again when save data)

So i notification to you this issue, hope it improve in future version.

Regards

**Comment by revolist** [comment]
Should be fixed in v4
