### ISSUE TITLE
Typo on custom range event

### ISSUE THREAD

**Issue by franz-josef-kaiser** [revolist/revogrid#250]
See [`src/component.d.ts`](https://github.com/revolist/revogrid/blob/55cab732d233df7f04ecb881e3075967edb6b9d6/src/components.d.ts#L504):

```js
/**
 * Before range apply. Triggered before range applied. Use e.preventDefault() to prevent range.
 */
"onBeforeaange"?: (event: CustomEvent<Selection.ChangedRange>) => void;
```

`onBeforeaange` >> `onBeforerange` (or maybe `onBeforeRange`?)

**Comment by alinoil** [comment]
I have the same question, seems to be a typo. Can this be confirmed? @revolist
