### ISSUE TITLE
Dynamic appended column has wrong size

### ISSUE THREAD

**Issue by sospartan** [revolist/revogrid#254]
**Describe the issue**
Last column dynamic added  always fill rest of grid width, even with a `size` set.

**To Reproduce**
https://codesandbox.io/s/dynamic-add-column-7fe4u?file=/src/App.js

**Comment by ArturoWipe** [comment]
#### Added case

_On NuxtJS (VueJS engine)_

* as a user, navigating on a page where `revogrid` is used **→ no column size issue**
* go to another page, go the `revogrid` page again **→ last column size is not set accordingly**

#### Workaround (patch surgery type)

_Tested both locally (`^3.3.0`) and on your sandbox @sospartan_

```javascript
// Column definition
{
  // using both `size` and `autoSize=true` seems to do the trick
  size: 100,
  autoSize: true
}
```

**Comment by revolist** [comment]
Can not reproduce on v4, is that still an issue? if so please reopen
