### ISSUE TITLE
how to Sort  a numeric column  using cellCompare??

### ISSUE THREAD

**Issue by getmonyinfo** [revolist/revogrid#256]
cellCompare sorting numberic column seems not working as excepted.

[https://codesandbox.io/s/dfgsdfssdf-forked-fyfxb?file=/src/App.vue:1364-1375](https://codesandbox.io/s/dfgsdfssdf-gklli)

**Comment by franz-josef-kaiser** [comment]
I just opened the example [and switched to version `3.0.97+`](https://codesandbox.io/s/dfgsdfssdf-forked-cxb8w). The sorting still is off:

* 1
* 11.1
* 2.1
* 3
* 4
* 6
* 7

Seems like sorting only applies to the first "char" here?

**Comment by eddie-englund** [comment]
I'm using 3.2.8 and I can't get cellCompare to work at all either with vue 2

**Comment by revolist** [comment]
It is working correctly now in v4, let me know if new issues arise. 
https://codesandbox.io/p/sandbox/dfgsdfssdf-forked-qf6zgr

<img width="548" alt="Screenshot 2024-12-04 at 12 36 35 PM" src="https://github.com/user-attachments/assets/b66e1c72-1a23-4fd3-8a3e-5733373ed483">
