### ISSUE TITLE
document the cell renderer in more detail

### ISSUE THREAD

**Issue by martindemello** [revolist/revogrid#259]
It would be helpful if the cell renderer documentation included some more details about the callback function, something along the lines of:

The `props` argument provides access to the column, row, and cell properties. See `ColumnDataSchemaModel` in the interface file for details of the data provided.

**Comment by van-huyen** [comment]
Hi @martindemello 

props is Object has:
 - column: column property like size, filter, sort, pin, drag, read only, column name, column logic name, cellTemplate, cellProperties...
 - data: grid data source
 - model: row data  ( data[index] )
 - prop: column logic name
 - rowIndex: row index

please reading it in debug mode on chrome:

![image](https://user-images.githubusercontent.com/83264685/148474148-dcef76e2-aee4-4fd6-a301-25dfeceba02e.png)

**Comment by martindemello** [comment]
hi @van-huyen , i figured it out by reading through the code, my point is that i should not have had to resort to that (or to looking up the chrome debugger), it should have been in the documentation.

**Comment by van-huyen** [comment]
I agree. Currently, the documents explain only about 30%.
Maybe the development team doesn't seem to have time.

**Comment by revolist** [comment]
Documentation was updated in v4
