### ISSUE TITLE
Drag and copy the cell data

### ISSUE THREAD

**Issue by nageswari** [revolist/revogrid#264]
What is the property to add drag and copy the cell to another cell?
It's there in the demo but not in the documentation.

Thanks.

**Comment by van-huyen** [comment]
that is "range" property in v-grid, help you select range cells and **auto-fill data** like excel.

![image](https://user-images.githubusercontent.com/83264685/148473470-c4a47548-9bb8-4781-a21b-d5810cce5881.png)

**Comment by m2a2x** [comment]
Hi @Karan9615-off 

You can use any of it and prevent default at any point

beforerange
beforerangeedit
beforeautofill

**Comment by Karan9615-off** [comment]
> Hi @Karan9615-off
> 
> You can use any of it and prevent default at any point
> 
> beforerange beforerangeedit beforeautofill
> 
> Check events for more details https://rv-grid.com/guide/api/revoGrid.html#Events

The preventDefault will stop range selection right, 
I want to prevent the range selection direction

**Comment by m2a2x** [comment]
@Karan9615-off at this point the right thing to do would be to catch settemprange event
https://rv-grid.com/guide/api/overlay.html

this event would allow you to control temp range selection
and after this use beforeautofill to change data to force only selected range to be saved

**Comment by Karan9615-off** [comment]
> @Karan9615-off at this point the right thing to do would be to catch settemprange event https://rv-grid.com/guide/api/overlay.html
> 
> this would allow you to highlight any area you want during selection and after this use beforeautofill to change data to force only selected range to be saved

Thanks @m2a2x It is very helpful.

**Comment by m2a2x** [comment]
> > @Karan9615-off at this point the right thing to do would be to catch settemprange event https://rv-grid.com/guide/api/overlay.html
> > this would allow you to highlight any area you want during selection and after this use beforeautofill to change data to force only selected range to be saved
> 
> Thanks @m2a2x It is very helpful.

Sure, keep us posted!
