### ISSUE TITLE
Functional Test Automation of the RevoGrid? HELP

### ISSUE THREAD

**Issue by garytafoya** [revolist/revogrid#265]
This technically isn't an issue but I'm not sure where to start.

The application my company is developing is planning to use the RevoGrid. As a Quality Assurance Engineer on the product I develop the automated tests for the functionality. I did some experimental automation using the sample grid on the revogrid website and found it almost impossible to automate any types of meaningful actions, primarily due to how the grid partially renders the data in the grid "as needed".

Things I's like to be able to do is:
- get the number of rows of data (total, not rendered)
- get a row of data (full row, not rendered)
- get a value from a row, column (even if it's not rendered)
- That's just the beginning.

Is the team at Revogrid familiar with any successful test automation implementations or can you suggest any tools or ideas on how to interact and validate with the grid? Or can you point me somewhere else where I can find more information?

Thanks!
-Gary

**Comment by garytafoya** [comment]
Thanks. Found a solution.

**Comment by nellb28** [comment]
@garytafoya how were you able to solve this?
