### ISSUE TITLE
Read Only Column Type

### ISSUE THREAD

**Issue by muenzer** [revolist/revogrid#266]
Is it possible to set an individual column as read only?  Could this be done through a custom column type?

**Comment by van-huyen** [comment]
Yes, you can set any column as read only mode, 
or special cell only as read only by row data (sample with rowData.id == 1) or by function.
![image](https://user-images.githubusercontent.com/83264685/142333524-a53adbdc-ab95-4195-b33e-0b5f29e2c521.png)

**Comment by muenzer** [comment]
Perfect.  Thanks.
