### ISSUE TITLE
Help wanted: possible to do virtualised list

### ISSUE THREAD

**Issue by mike-hogan** [revolist/revogrid#267]
This is not an issue, it's a request for help.  

If I have many many rows, is there some way to do a virtualised scrolling?  Or does revogrid currently expect to get all the data?

I see pagination is on the roadmap, but am asking specifically about virtualised (infinite) scrolling.

Thanks,
Mike.

**Comment by van-huyen** [comment]
Did you mean delayed loading data, i have seen it in "to do list", maybe it will ready in version 4.0.
In my case, i'm loading a part of all data, and load all data later (lazy load), then update result of all data when it ready.
![image](https://user-images.githubusercontent.com/83264685/144007969-fe1f5ee1-cc6b-4b7e-8c9c-796688e29f07.png)

**Comment by revolist** [comment]
It's going to be part of Pro examples in v4. It's same as pagination but with no clicks.
