### ISSUE TITLE
Major bug: Input does not apply when user clicks away from cell!

### ISSUE THREAD

**Issue by MaximeKoitsalu** [revolist/revogrid#269]
**Check if issue exists**
Search the repo and ensure your issue doesn't already exist. If so, it may:
- Have already been fixed in an unreleased version.
- Have been closed without a solution. Please create a new issue instead of commenting on the old one.

**Describe the issue**
See the gif below:
![revogrid-bug](https://user-images.githubusercontent.com/8655862/143546808-b7f74f06-644e-4d50-a0fb-0c0deaa1198f.gif)

**To Reproduce**
Create a minimal reproduction to illustrate the issue. Here's a [template](https://codesandbox.io/s/revo-grid-vanilla-js-7cq7c) to start you off.

**Comment by van-huyen** [comment]
please flow this: https://github.com/revolist/revogrid/issues/201#issuecomment-945224716

**Comment by ArturoWipe** [comment]
> please flow this: https://github.com/revolist/revogrid/issues/201#issuecomment-945224716

If we are using a custom template/editor (eg. ""revogrid-column-numeral"), this workaround will not execute the custom business.

**Comment by revolist** [comment]
https://rv-grid.com/guide/api/revoGrid.html v4
