### ISSUE TITLE
how to create this table using revogrid in vue

### ISSUE THREAD

**Issue by darkhorse07232020** [revolist/revogrid#270]
Hello.
I tried to build the table like this using revolist in vue, but can't customize the first row cells.
How can I implement this?
Thanks
![2021-11-26_23h00_49](https://user-images.githubusercontent.com/67903345/143625627-e79c5a4a-0ab9-4e5c-8dc2-c1b498e114fe.gif)
.

**Comment by van-huyen** [comment]
let try "Pinned rows", custom row data and pin it in top
https://revolist.github.io/revogrid/guide/rows.pinned.html

**Comment by revolist** [comment]
Closing 'coz of inactivity
