### ISSUE TITLE
Row Indentation

### ISSUE THREAD

**Issue by MentalGear** [revolist/revogrid#272]
Within a tree structure, I would like to have the visual representation of indented rows, not just the text within the first cell to be indented with margin-right. Example:

<img width="666" alt="Screenshot 2021-12-12 at 12 01 01" src="https://user-images.githubusercontent.com/2837147/145709708-b754fda4-6093-4943-b028-fd25c3770e81.png">

Would that be possible with Revo?

**Comment by van-huyen** [comment]
Hi @MentalGear 

Did you mean tree view ? follow this:
https://revolist.github.io/revogrid/demo/jsx.tree.html
![image](https://user-images.githubusercontent.com/83264685/148475978-479c7a46-0ac1-45fe-a9f9-875ac8a335c0.png)
