### ISSUE TITLE
How to set focused cell(s)

### ISSUE THREAD

**Issue by jtrepagne** [revolist/revogrid#274]
Hello. Firstly, thanks for your great work !

I am currently facing an issue with the cell selection of revogrid. I would like to control which element is focused. I would like do so by using a method and/or by reacting to events (or keyboard actions), but I can't find a proper way to do it.

My needs would be, for example,  to move left on "shift + tab" keypress event and move to the right when a cell value change event occurs. This would result in a more "excel like" behavior and efficiency for user.

Am I missing something ? If not, would it be possible to implement this as a feature ?

Thank you a lot.

**Comment by JulienGrv** [comment]
I was looking for this the other day and I also did not found a function for that. I think related code is part of the viewport, it just requires implementing a function in the revogrid component

**Comment by JulienGrv** [comment]
It's actually available in the branch `next`, see also this commit [here](https://github.com/revolist/revogrid/commit/a09caef6891d687a0b2864702195913d5ad94df4).

**Comment by jtrepagne** [comment]
> It's actually available in the branch `next`, see also this commit [here](https://github.com/revolist/revogrid/commit/a09caef6891d687a0b2864702195913d5ad94df4).

I just checked out next branch and this is working wonders. Thanks a lot 👍
