### ISSUE TITLE
No grid displayed in VueJS 3 project

### ISSUE THREAD

**Issue by eugenevk** [revolist/revogrid#278]
In my VueJS 3 project (@vue/cli 4.5.15), no grid is being displayed, although if I look in the console, I can see the grid html tags.
I have created a github repo to reproduce this: https://github.com/eugenevk/revogrid.git

Screenshot:
![image](https://user-images.githubusercontent.com/19785727/147070216-1512273e-3cc2-40b7-92c0-6b9747b936f3.png)

The VueJS component:
```
<template>
  <div id="app">
    <v-grid theme="compact" :source="rows" :columns="columns"/>
  </div>
</template>

<script>
import VGrid from "@revolist/vue3-datagrid";
export default {
  name: "App",
  data() {
    return {
      columns: [{
          prop: "name",
          name: "First"
        },
        {
          prop: "details",
          name: "Second"
      }],
      rows: [{
        name: "1",
        details: "Item 1"
      }]
    }
  },
  components: {
    VGrid
  }
}
</script>
```

**Comment by JulienGrv** [comment]
Since you are using Vue (and perhaps Vite), you might like to lool at this example repository [here](https://github.com/revolist/vue3-revolist-vite).

**Comment by MXNDEVCND** [comment]
same here

**Comment by seokman-hong** [comment]
same here

**Comment by softrain73** [comment]
same here

**Comment by kyhou** [comment]
for me it is not even generating the html tags:
`<v-grid theme="compact" source="[object Object],[object Object]" columns="[object Object],[object Object],[object Object]"></v-grid>`

**Comment by tobiasBora** [comment]
One need to use the style:
```
revo-grid {
    height: 500px;
}
```
to make it visible… but can’t the height automatically adapt to the content?

**Comment by faltenberg** [comment]
Same here. Got it fixed with the absolute height as proposed by @tobiasBora. Still sad, that it still cannot calculate its height automatically. :(

**Comment by IvanPrat** [comment]
This issue seems to be happening because of a `height: 0px;` in `.main-viewport`
You can fix it adding this to your stylesheet:

```
revo-grid .main-viewport {
  height: auto;
}
```

**Comment by revolist** [comment]
Should be ok in v4+
