### ISSUE TITLE
[Why] After `yarn prettier`, modified so many files.

### ISSUE THREAD

**Issue by lijie1129** [revolist/revogrid#279]
branch: `Master`

![image](https://user-images.githubusercontent.com/5371749/147212026-6405d848-9b10-4b33-ad50-48f5e1d721d5.png)

**Comment by jarone** [comment]
er... 

The `yarn prettier`  is the correct linter command for Revogrid, right?

**Comment by revolist** [comment]
It's source code modification, it seems you have different local settings from project.
