### ISSUE TITLE
Save data when losing focus from cell

### ISSUE THREAD

**Issue by dennisgeerts** [revolist/revogrid#280]
As can be seen from the demo (https://revolist.github.io/revogrid/demo/), when the cell contents is changed and without clicking enter, click with the mouse on another cell, the inputted value is not saved. 
How do i save the value when focus from cell is lost without pressing the enter key ?

**Comment by van-huyen** [comment]
![image](https://user-images.githubusercontent.com/83264685/148469031-cfbbbe6d-b3a6-41b0-8106-3528778bef75.png)

**Comment by sonikdesign** [comment]
It would be better to have a boolean at the grid level to allow cell editing also losting cell focus (by clicking on another cell or outside the grid), not only via ENTER or TAB key.

**Comment by sonikdesign** [comment]
> ![image](https://user-images.githubusercontent.com/83264685/148469031-cfbbbe6d-b3a6-41b0-8106-3528778bef75.png)

Here my code for Vue3. For now I prefer send `$refs.vgrid` via @focusout event. I found problems with Vue3 (in Typescript) and $refs objects. For now this is my dirty way.

```html
<!-- template -->
<v-grid
ref="vgrid"
@beforeeditstart="onBeforeEditStart"
@focusout="onFocusOut($event, $refs.vgrid)"
...
/>
```

```javascript
// script
setup () {
  let gRowIndex = ref(0)
  let gColName = ref('')

  const onBeforeEditStart = (e: CustomEvent<{ rowIndex: number, prop: string } >) => {
    gRowIndex.value = e.detail.rowIndex
    gColName.value = e.detail.prop
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const onFocusOut = async (e: any, vgrid: any) => { // I don't know about this event, no docs
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    let viewData = await vgrid.$el.getVisibleSource()
    viewData[gRowIndex.value][gColName.value] = e.target.value
  }

  return {
    onBeforeEditStart,
    onFocusOut
  }
}
```

**Comment by dennisgeerts** [comment]
Thanks for the code snippet. It works great.
However when used in combination with the "**range**" property, the value is only updated after clicking the second time away from the cell. 
The first time, the value is saved, but the old value remains visible, when clicking again on yet another cell, the changed value will show.
How do I solve this issue ?

**Comment by lionsarmor** [comment]
I am using vue2 and having a problem figuring out how to capture the rowDragStart event, I really need to figure out how to make multiple columns drag at once

**Comment by van-huyen** [comment]
@lionsarmor  
I think revo-grid has row drag function only, i don't know column drag function
For using row-drag:
1. add property "canDrag" in v-grid tag
![image](https://user-images.githubusercontent.com/83264685/156956568-f0c0c3f2-3607-4f3b-9504-98ecae419006.png)

2. add property "rowDrag" in column defined (maybe multil columns, but it is for rowDrag function)
![image](https://user-images.githubusercontent.com/83264685/156956526-770e8767-19b8-4ae6-a711-029bd933afa0.png)

**Comment by maranyil** [comment]
I'm using vue 2, but can't make the focusout work. Can anyone help me, please?
