### ISSUE TITLE
How to generate a new theme

### ISSUE THREAD

**Issue by Captain-Justin** [revolist/revogrid#285]
![image](https://user-images.githubusercontent.com/26615255/150673114-55c51828-d06f-49ec-b2d5-52ef54d3cf8d.png)
![image](https://user-images.githubusercontent.com/26615255/150673188-510eccd6-0574-4492-b772-42f90d1ba91f.png)

like that,rebuild the default stylesheet and customize various aspects of the framework for my particular needs.

**Comment by PlayApple** [comment]
@Captain-Justin 
Hello, how did you finally solve this problem? I also noticed that treelab's < revo-grid / > component has many more properties than it does on github. such as canaddcolumn="true"、cabreordercolumn="true".

**Comment by m2a2x** [comment]
Treelab's project states as a highly customized version of the grid.
I think what was done it is a narrow version for their project, but anyway they decided to keep it private and not share with community. 

Currently there is no way to define new theme without grid core code customization, this is what was done by treelab. You could always fork it and replace existing theme with your own but problem you'll have it will not be supported. I suggest just to change styles on the grid and pass row sizes on your own.

You can PR feature of support custom theme any time and it would be appreciated by community.
