### ISSUE TITLE
Remote virtual scrolling, data loaded from the server, any example

### ISSUE THREAD

**Issue by Wyzix33** [revolist/revogrid#290]
**Describe the issue**
Hi, I'm trying to use revogrid to display 1 million+ records, i have a working API that can serve "pages" of rows (array of objects) using filters, sorts and offsets. Can this library get data and still use filters and sorts on that data if the data is remote?
Or how would you display this data in revogrid, because downloading it all would take about 1-2 minutes..

Thanks

**Comment by revolist** [comment]
@Wyzix33 What you have todo:

1. Create an empty array with length equal to all rows. new Array(100000000)

2. In cellTempate you have information which row was requested

3. Load initially 1k items

3 when you go farther then 500 load 1k more and mutate array

**Comment by Wyzix33** [comment]
So there is no way i can only request and display only visible rows?
And what about filtering/sorting how will this be achieved, in my initial script i load first page, about 50 rows (latest added), then after the user sets some filters or sort the results i send the request for the first 50 rows that result after applying those filters...
Also, setting a filter will change initial array length (usually fewer rows ) and scroll height should reflect that...
So the data request should be a promise function where i must have access to filters, sort and rows to display, this request should also use debouncing, so that if a user scrolls really fast it should only get the rows couple of ms after scroll stops and display a loading or something while scrolling...  Is this possible?

Thanks

**Comment by revolist** [comment]
Hello, it is still not conflicting with the approach I have described above.

But it will require a lot of implementation on your side.

1. You will have to do server side filtering, grid is fully reactive, when you filter something you can to remember scroll position and you can scroll to position or index you want, but I don't think it is user friendly 

2. Also it is very specific per project, we didn't work on server loading plugin hence we are focusing now on other functionality.

**Comment by Wyzix33** [comment]
Thank you for your response, it seems i need to start working on a custom solution for my needs :)
