### ISSUE TITLE
Variable heights posible?

### ISSUE THREAD

**Issue by Wyzix33** [revolist/revogrid#291]
**Describe the issue**
Can rows heights be content aware or hard-coded (different heights / row) ? Just like table behavior, if a cell has multiple lines of text and fixed width row height will increase.

Thanks

**Comment by van-huyen** [comment]
did you mean row-height auto grow-up by content?
i think grid has no feature for that, 
in my case, i creating the tooltip for reading long text in cell by mouse move event.

**Comment by Wyzix33** [comment]
ok, thank you, it seems i need a custom solution for my needs, this one is too generic and only focused on local data...
