### ISSUE TITLE
[question] Is there an API here to help set the uuid for each row?

### ISSUE THREAD

**Issue by lijie1129** [revolist/revogrid#292]
Hi, everyone~

## Background

I am working on a **multi-person collaborative** scenario, where the cells and rows of the `Revo-grid` are arranged based on **indexes** by default, which may not be suitable for a multi-person scenario.

## For example

When a user is editing a cell in a row with index 1, another user has already dragged the row (index 1 row) and modified the index (the modified index is 2).

## Question
Therefore, I think that identifying each row by its UUID (like the prop attribute of a column), and modifying the contents of a cell by the UUID of the row to locate it may be more suitable for a multi-person collaboration scenario.

The question is: how to customize the UUID for each row?

> except `rowClass`, I think it should be used to about style's purpose and the value of `rowClass` can be duplicated.

**Comment by revolist** [comment]
You can store row id inside of row model, you don't need to store row index, you can compare ids you have, you don't need html based ids, all should be data based.

**Comment by lijie1129** [comment]
Thanks for the advice, it got me out of the rabbit hole.
