### ISSUE TITLE
[help wanted] drag and drop multiple rows and capturing row drag event.

### ISSUE THREAD

**Issue by lionsarmor** [revolist/revogrid#295]
I do not know how to use events, my main goal is to use drag and drop on multiple rows using vue 2, but so far I am unable to trigger any events, I saw in a related issue that i could update the collection but am confused about that as well, this is what I have : 

    <v-grid
      theme="darkCompact"
      :source="rows"
      :columns="columns"
      resize="true"
      row-headers="false"
      rowClass="row_color"
      rowSize="25"
      readonly="false"
      filter="false"
      id="vtable"
      @rowdragstart="test()"
      @headerclick="test()"
      @viewportscroll="test()"
      @roworderchanged="test()"
      @aftercolumnresize="test()"
    />
---
methods: {
    test() {
      alert("test");
    },
    newDataColumns(value) {
      this.columns = null;
      this.columns = value.columns;
    },
    newRowData(value) {
      this.rows = null;
      this.rows = value.rows;
    },
}

they should call a method, but nothing happens, I think I am doing this wrong any help would be appreciated.

**Comment by van-huyen** [comment]
I tried using the rowDrags event (to automatically save the data for each drag) but it didn't work, so I gave up.

**Comment by lionsarmor** [comment]
thanks, yea I am having trouble even figuring out what events are supposed to trigger on a row drag, thinking I could make a way for linked rows to update in some other way that I could create, but I just cant seem to get tat rowDragStart (rowdragstart)  to do anything.

**Comment by revolist** [comment]
@lionsarmor rowdragstart is the right event to subscribe. To make it work make sure you have drag icon, to make it visible don't forget to use 

```
interface ColumnRegular {
rowDrag?: boolean | {
    (params: ColumnDataSchemaModel): boolean;
}
```

**Comment by revolist** [comment]
We are out of resources to work on documentation at this moment. It is much faster to check such things straight in component's code:

`cellRenderer.tsx`

**Comment by revolist** [comment]
To drag multiple rows you will have to remember how many rows selected, at this point you need to check in your app when you select/deselect something. And when you finish drag on `roworderchanged` you prevent original order and apply your own.

**Comment by lionsarmor** [comment]
thank you!
