### ISSUE TITLE
column Select type: how to show value outside source

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#296]
Hi @revolist 

How can i display value on column select type when value not found in source ?

Example: using select column for show user name by user code (about 10 000 users)
- 2008: user001 has created some data (save user001 code in table AAA)
- 2012: user001 has quit job, and user001 has been deleted from table user
- 2022: show all data, has data create by user001 (table AAA), but now user001 not exist in select source (table user)

![image](https://user-images.githubusercontent.com/83264685/156965773-e2e8c721-496c-412f-942b-734e2ffca7d2.png)

**Comment by revolist** [comment]
hello @van-huyen 
trying to understand question but it is a bit confusing for me.

based on error you just have no data in render datasource to read from. It that problem from https://github.com/revolist/revogrid-column-select?

What has to be done probably you just need to remove user from grid datasource if it is no longer there.

**Comment by van-huyen** [comment]
hi @revolist , sorry for the confusing question.

Context example: In production, user creates an account and buys something on web => invoice has user code.
After that, User delete account => you can not delete all invoices of that user (accounting - financial)

Example for [revogrid-column-select](https://github.com/revolist/revogrid-column-select)

select source: [ {value: 1, lable: 'aaa'}, {value: 2, lable: 'bbb'}, {value: 3, lable: 'ccc'}, ] 
grid datasource of column select has value: 1, 2, 3, **_4_**, 5... 

Maybe now of process to show label on column select: 
  label =  [select source].filter((r) => { return r.value == **_4_** })[0].label => undefined => error 

Expected behavior: if has not data in select source, show itself.
 label =  [select source].filter((r) => { return r.value == **_4_** })[0].label  ||  **_4_**

**Comment by van-huyen** [comment]
Yes, data should be kept consistency. But we create apps for human use, not for computer or machine, LOL.

I don't know how to pull request, so I'm using patch-package.
I tried to fix this problem in this line code and rebuild, it is working: **Show value when value not in source lookup.**

`    if (col.labelKey && col.sourceLookup && col.sourceLookup[val]) {`

![image](https://user-images.githubusercontent.com/83264685/158912661-73b3c881-0a1a-4f94-9996-4e7f20af1c8d.png)

**Comment by revolist** [comment]
Seems no longe an issue
