### ISSUE TITLE
Multi-select cells working for version 2.9.7 but not later versions

### ISSUE THREAD

**Issue by mwedmark** [revolist/revogrid#297]
I was looking for this nice feature to be able to multi-select cells using Mouse Drap'n'Drop. This worked in your example but not locally. After trying everything out I noticed that ONLY 2.9.6 and 2.9.7 works with that and in later versions this was removed again. I did not find any release notes about this being removed. Is it a bug? Anyone know how to add it back in?

**Comment by van-huyen** [comment]
You mean like this, I'm waiting too.
https://github.com/revolist/revogrid/issues/142#issuecomment-846669331

Like natee answer, "You can press and hold the shift button" for select multi cells in latest version.

**Comment by m2a2x** [comment]
Hello guys, it is working in next 4+ version but it is not well tested yet to be released yet
Working on fixing issues and updates there

https://github.com/revolist/revogrid/tree/next
