### ISSUE TITLE
[Feature Request] Select range of multiple rows and columns at the same time

### ISSUE THREAD

**Issue by hunterwilhelm** [revolist/revogrid#299]
I would like to select multiple rows and columns like you can in excel and copy them into excel. 

This topic was mentioned in [Issue #264](https://github.com/revolist/revogrid/issues/264) but the demo in question only allows you to select multiple cells in the same row. 

Here is a demo of what I am talking about. See how you can't select all 4 cells? only 2 at a time? If I want to select all 4, I have to use the handle to overwrite some of the columns, defeating the purpose of trying to select them.
https://codesandbox.io/s/react-revo-grid-working-94swom?file=/src/App.tsx

**Comment by alinoil** [comment]
This would be a very nice addition. It seems to be possible already but only sometimes.
Check the official Main Demo where it works in some columns but only if you drag from south to north. 
Never seems to work if I try to select a range from north to south
https://revolist.github.io/revogrid/demo/
![image](https://user-images.githubusercontent.com/6596304/175542575-5859abc2-c77d-4df6-9b82-753304167b74.png)

**Comment by revolist** [comment]
The range should work well from v4
