### ISSUE TITLE
add a link to the esm module docs in the guide 

### ISSUE THREAD

**Issue by martindemello** [revolist/revogrid#301]
This [issue with vite](https://github.com/revolist/revogrid-react/issues/6) is not react specific, and is fixed by following https://github.com/revolist/revogrid/blob/master/docs/custom.element.md

There is a section in the README about that, but the doc should be either linked to or inlined in https://revolist.github.io/revogrid/guide/installing.html as well.

**Comment by m2a2x** [comment]
Hello @martindemello, thank you for this improvement request.

You can send PR for it here, we'll merge it:
https://github.com/revolist/revogrid-vuepress

**Comment by revolist** [comment]
There is no issues with vite in v4 all elements are esm oriented
