### ISSUE TITLE
The last columns were broken

### ISSUE THREAD

**Issue by van-huyen** [revolist/revogrid#304]
Hi Revolist team,
Some time the last columns were broken because "horizontal scroll" or "row-header auto grow up" or "grid's width" like this:
![image](https://user-images.githubusercontent.com/83264685/159382120-2e928a7f-8771-4f72-8d3c-c886f942ce0c.png)

Temporarily, I tried adding the column size to fix it.

**Comment by m2a2x** [comment]
thanks, need to check it
any specific steps?

**Comment by van-huyen** [comment]
when some last columns size is small (40px)
![image](https://user-images.githubusercontent.com/83264685/160306016-f188f0d6-3513-480b-84d1-0ac5872f9137.png)

**Comment by van-huyen** [comment]
the next column has disappeared
![image](https://user-images.githubusercontent.com/83264685/160306655-0c7b2010-e0c9-4e3d-b9e3-802d8405727e.png)

**Comment by m2a2x** [comment]
Got it, thanks @van-huyen

**Comment by c4b4d4** [comment]
I'm getting this same issue. 

<img width="259" alt="Screenshot 2022-12-07 at 16 10 45" src="https://user-images.githubusercontent.com/375183/206296585-bca3f9ac-c5a3-43a6-961b-6366d319a73d.png">

What file/part of the code is dedicated on calculating available space? To check what's going on.

**Comment by sven42** [comment]
Sometimes the content in the header and the cells of the last column is not displayed. 

- Using the same table structure and just other column names (by changing language) can toggle the effect. 
- Editing is possible, however: the edited values only show up while editing.

My workaround is to add an extra Column at the and named "   " (3 Spaces)

**Comment by revolist** [comment]
Can not reproduce on v4. We were fixing multiple rendering problems, should no longer be the case.
Please update us if any issue like this arise.
