### ISSUE TITLE
ColumnTemplate jsx does not re-render

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#310]
**Describe the issue**
I made a custom columnTemplate where on click I toggle color from green to red. The columnTemplate does not re-render on click. However, if I click, then go and click on a cellTemplate, that causes a full re-render of the cells and columns.
VGridTemplate works as well, but there's this issue: https://github.com/revolist/vue-datagrid/issues/31 and I don't feel confortable using it. 

**To Reproduce**
https://codesandbox.io/s/revogrid-vuecomponent-forked-exjhyl?file=/src/App.vue

**Comment by revolist** [comment]
Should be fixed in v4.
