### ISSUE TITLE
Invalid width column property in react version

### ISSUE THREAD

**Issue by PlayApple** [revolist/revogrid#312]
https://codesandbox.io/s/revogrid-react-component-hrgrx?file=/src/App.js

In react demo, I found that the width property is invalid. I have the same problem in practical use.

![image](https://user-images.githubusercontent.com/3360969/166900351-9aaac2c8-3425-44ec-adcf-6f6f661af96a.png)

**Comment by Buroni** [comment]
The property is named `size`, not `width`. See https://revolist.github.io/revogrid/guide/column.resize.html
