### ISSUE TITLE
Fixed columns needed

### ISSUE THREAD

**Issue by BenjaminVockenberg** [revolist/revogrid#314]
Hello community,
I've only recently started using revogrid. I couldn't find my needed functionality in the documentation.

My data for the project creates a huge amount of columns. The first column is the person's name. The more I scroll to the left, the more trouble I have staying in the right row. So it would be very nice if there was a way to pin the first column so I can see that the data relates to the right person.

I saw that it is possible to have pinned rows, so I think it would be nice to have pinned columns as well.

Thanks for reading. Have a good and healthy time

**Comment by DavidCF98** [comment]
Hello! 

You can fix the first column like this:

Example: 

const columns: any = ref([
 {
   prop: "hello",
   name: "Hello",
   columnType:"string",
   **pin: 'colPinStart"** 
 },

_more columns..._
