### ISSUE TITLE
How to programmatically sort the grid?

### ISSUE THREAD

**Issue by bbbford** [revolist/revogrid#315]
I would like to save the sort order of my grid, so that I can display it the same way when the user returns.

I attempt to get the sorting order via the "beforesorting" event. This event gives me column name, order, prop.

I would later like to apply this same sorting order to the grid. I attempt to use the "updateColumnSorting" method. This method takes a column index, which is not provided, so I attempt to find the column index.

I call the "updateColumnSorting" method, which correctly shows the sort indicator, but the data in the grid is not actually sorted.

How can I programmatically sort the grid?

Here is sandbox link - https://codesandbox.io/s/revogrid-programmatic-sort-z4yn9i?file=/src/Grid.vue

**Comment by Yiidiir** [comment]
@revolist Any insights here?

**Comment by revolist** [comment]
Hey, you could simply access plugin (getPlugins method) for sorting and use as `runSorting`
https://github.com/revolist/revogrid/blob/main/src/plugins/sorting/sorting.plugin.ts
