### ISSUE TITLE
vue-datagrid fails after install in vue2 project

### ISSUE THREAD

**Issue by PerpetualWar** [revolist/revogrid#317]
I'm working on this Vue2 project with composition api and typescript added. After installation of `@revolist/vue-datagrid`, and importing in the component where I wanna use it I got bunch of TS errors from the start:

```
@revolist/revogrid/dist/types/interfaces.d.ts(267,27):
267:27 Cannot find name 'HTMLRevoGridElement'.
    265 | export declare namespace RevoPlugin {
    266 |   class Plugin {
  > 267 |     constructor(revogrid: HTMLRevoGridElement, ...[]);
        |                           ^
    268 |     destroy(): void;
    269 |   }
    270 | 
```

```
7:128 Cannot find namespace 'JSX'.
     5 |     install: typeof install;
     6 | };
  >  7 | export declare const VGridVueTemplate: (cntr: import("vue").VueConstructor<import("vue").default>) => (h: Function, p: any) => JSX.Element;
       |                                                  
```
```
15:43 Cannot find namespace 'JSX'.
    13 |     componentDidRender(): void;
    14 |     disconnectedCallback(): void;
  > 15 |     render(h: RevoGrid.HyperFunc<VNode>): JSX.Element;
       |                                           ^
    16 |     private renderAdapter;
    17 | }
```
I tried both latest 3.1.6 version and also 2.9.9. same problem.

Any ideas what is wrong here?

**Comment by m2a2x** [comment]
@PerpetualWar seems like something is messing with your typing.
I can try to check if you make sample somewhere on https://codesandbox.io/

**Comment by PerpetualWar** [comment]
I fixed this by enforcing TS to ignore node_modules typings: `"skipLibCheck": true,`.

Still I would like to disable typings only for this lib.

Help is appreciated.

**Comment by revolist** [comment]
No longer present problem in v4 full ts support for vue 3 and vue 2
