### ISSUE TITLE
How to update source

### ISSUE THREAD

**Issue by edutucci** [revolist/revogrid#321]
In my page I get data from database or other method in onMounted() but the grid does not refresh data.

**Comment by disqrl** [comment]
did you find a solution? (have the same trouble)

**Comment by oussamalkd** [comment]
@edutucci  did you found a solution for this?

**Comment by disqrl** [comment]
> @edutucci did you found a solution for this?

I found solution, do you want code?

**Comment by oussamalkd** [comment]
> > @edutucci did you found a solution for this?
> 
> I found solution, do you want code?

Yes, please.

**Comment by disqrl** [comment]
> > > @edutucci did you found a solution for this?
> > 
> > 
> > I found solution, do you want code?
> 
> Yes, please.

here is example https://github.com/disqrl/vue3-revogrid/blob/main/src/pages/InitiatorEdit.vue

**Comment by oussamalkd** [comment]
> > > > @edutucci did you found a solution for this?
> > > 
> > > 
> > > I found solution, do you want code?
> > 
> > 
> > Yes, please.
> 
> here is example https://github.com/disqrl/vue3-revogrid/blob/main/src/pages/InitiatorEdit.vue

Thanks, mate
