### ISSUE TITLE
Row edit, multiple cells in edit mode at a time

### ISSUE THREAD

**Issue by jaredliw** [revolist/revogrid#322]
What I want to achieve:
![image](https://user-images.githubusercontent.com/57293776/172045817-ca317eba-09e8-4a5a-9eb0-25ce1bc88cc3.png)
_(Screenshot was taken from: https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml?jfwid=bf6c6)_

When the :pencil2: button is clicked, I call `grid.setCellEdit(rowIndex, prop);` n times, with different props. However, only the cell in the last column is in edit mode.

Wanna ask, is there a way to let multiple cells persist in edit mode before the :white_check_mark: button is pressed?
Thanks in advance.

**Comment by revolist** [comment]
There is a way to do this with plugin and merge row pro feature or you can simply use custom render with inputs inside
