### ISSUE TITLE
How to pass user props to vue cell template ?

### ISSUE THREAD

**Issue by duese1990** [revolist/revogrid#324]
Hi,
I am using vue framework and like to pass user props to a vue cell template.

`tableColumns: [{`
  `   name: "Actions",`
  `   prop: "amsRecid",`
  `   cellTemplate: VGridVueTemplate(CellActions)`
`}]`

Is there any possibility like

`userProps: {userProp1: 'Test 1', userProp2: 'Test 2'}`
`cellTemplate: VGridVueTemplate(CellActions, userProps)` ?

And then inside cell template:

`...`
`props: ["rowIndex", "prop", "userProp1", "userProp2", ...],`
`...`

**Comment by duese1990** [comment]
Hi madesigne,

thank you for reply!
It's working! I can pass a prop:

`cellTemplate: VGridVueTemplate((VNode) => h(CellActions, {msg: 'Test msg'}))`

Inside CellActions:
`props: ["msg"]`
`mounted() { alert(this.msg) }`

But now, the "original standard props" of `cellTemplate: VGridVueTemplate(CellActions)` are lost. For example "rowIndex".

You already wrote that it is possible to pass table data - could you explain how? I need it like that:

`cellTemplate: VGridVueTemplate((VNode) => h(CellActions, {msg: 'Test msg', rowIndex: rowIndexFromTable}))`

Thank you in advance! =)

**Comment by duese1990** [comment]
This works, but I'm using

`cellTemplate: VGridVueTemplate(CellActions)`

because of other issues):

`cellTemplate: VGridVueTemplate((VNode) => h(CellActions, {msg: 'Test msg', rowIndex: VNode.rowIndex}))`

**Comment by marcos-vinicius-dev** [comment]
Hello. Thanks a lot for the help. However, my VGridVueTemplate doesn't change when browsing the list.

**Comment by duese1990** [comment]
Hi marcos,

in some tables everything is fine and in others tables I had still the problem, but I could solve it by declaring my props inside cell template as reactive:

```
<template>
    <input v-model="text" class="h-75 rounded-sm" style="width:100%">
</template>

<script>
    import { defineComponent } from 'vue';
    import { toRef } from 'vue'

    export default defineComponent({
        name: 'InputField',
        props: [
            "rowIndex",
            "prop",
            "model",
            "data"
        ],
        setup(props) {
            const reactiveModel = toRef(props, 'model');
            const reactiveProp = toRef(props, 'prop');
            return { reactiveModel, reactiveProp }
        },
        data() {
            return {
                text: ''
            }
        },
        mounted() {
            this.$watch(
                (vm) => [vm.reactiveModel],
                (val) => {
                    this.text = this.reactiveModel[String(this.reactiveProp)].value;
                }
            );            
        },
    })
</script>
```
