### ISSUE TITLE
Encountering the following error when attempt to use revogrid with VueJS

### ISSUE THREAD

**Issue by mrcrittall2016** [revolist/revogrid#327]
Hi I am encountering the following error when using Vue 2 with revogrid:

![image](https://user-images.githubusercontent.com/19516138/174097318-a82fdfa9-13b5-494c-9e58-3d1d22e26b67.png)

Within the node_modules folder the file paths appear to be unrecognised e.g.

![image](https://user-images.githubusercontent.com/19516138/174097460-471922d4-39ff-41b8-83a3-c1e3b054b748.png)

Any ideas?

**Comment by revolist** [comment]
Seems types were broken. Please try v4.
