### ISSUE TITLE
Multi filter example

### ISSUE THREAD

**Issue by pyb0987** [revolist/revogrid#331]
Hi guys, first of all, congratulation for this great work.

I'm currently editing my project with this module thanks to you and I wonder if
there is an example of using multiple filters. across the columns or not. just an example of a form of 'filterCollection' would be appreciated.

**Comment by Yiidiir** [comment]
After days of debugging, here's how to filter a specific column on init of the grid:

```
     ColumnFilterConfig: {
          multiFilterItems: {"column_to_filter": [ {
              id: 1,
              type: 'contains',
              value: 'string_found',
              relation: 'and',
            }]}
          },
```
and then define the prop to the component, in Vue:

```
        :filter="ColumnFilterConfig"
```

Hope this helps!
