### ISSUE TITLE
Add new rows

### ISSUE THREAD

**Issue by disqrl** [revolist/revogrid#332]
Is there any way to add new rows into the v-grid? I tried to append array rows, but seems to be it doest work.
Could anyone explain me how to do that? Cuz there is not info in docs.

**Comment by paramula** [comment]
same issue

**Comment by kmukhamadulloev** [comment]
> same issue

Use this.
```
addRow() {
      const grid = this.$refs.grid.$el;
      this.rows.push({});
      grid.source = [];
      grid.source = this.rows;
}
```

**Comment by NotDemin** [comment]
its working but when the grid is scrolled it disapears, any fix ?
