### ISSUE TITLE
How to update data in VueCellTemplate?

### ISSUE THREAD

**Issue by chrisoprea** [revolist/revogrid#334]
When I change rows, the data in the cell does not change.

**Comment by duese1990** [comment]
Put your logic in computed and it should work.

`props: ["rowIndex", "prop", "model", "data"]`

```
computed: {
   backColor() {
      if(model.value > 3) {
         return 'yellow';
      } else {
         return 'red';
      }
   }
}
```

Generally you should provide a little bit more information.
