### ISSUE TITLE
Excel import

### ISSUE THREAD

**Issue by kmukhamadulloev** [revolist/revogrid#335]
Is there any way to import/export Excel file in this library?

**Comment by Shubham20015** [comment]
Yes you can export data to csv
Refer: https://codesandbox.io/s/revo-grid-vue3-forked-oibx2h?file=/src/App.vue

**Comment by disqrl** [comment]
> Yes you can export data to csv Refer: https://codesandbox.io/s/revo-grid-vue3-forked-oibx2h?file=/src/App.vue

I know about csv, but I need excel file import and export (mainly import)
Is there any way to make it? Or what about libs?

**Comment by Yiidiir** [comment]
@kmukhamadulloev you can use a library from your preferred framework to turn the import file to a collection you can set in `:source` prop

**Comment by revolist** [comment]
We've build excel Pro plugin example. Available in v4+
