### ISSUE TITLE
Feat request: aftercellfocus or aftercellblur event

### ISSUE THREAD

**Issue by satyavh** [revolist/revogrid#341]
**Describe the issue**
In order to validate cells, it would be very useful to have an `aftercellfocus` or `aftercellblur` event, so validation can happen after the cell has lost focus, regardless of whether an edit was created.

PS
Willing to make a PR if you point me in the direction I should be searching for these events

**Comment by revolist** [comment]
Hi @satyavh 
Sorry this request was lost in the history, we organically came to the same events in v4: afterfocus
