### ISSUE TITLE
Typo for event: "beforeaange" instead of "beforerange"

### ISSUE THREAD

**Issue by sven42** [revolist/revogrid#345]
Sourcecode uses beforeaange with one exception: 

https://github.com/revolist/revogrid/blob/2efc31f080c3abc720ccc097a9cdf61e4375b735/src/index.html#L143

**Comment by revolist** [comment]
https://rv-grid.com/guide/api/revoGrid.html
https://rv-grid.com/guide/api/overlay.html

no longer reproducible in v4

**Comment by revolist** [comment]
Hello @sven42 
thank you very much for the message, updated.
