### ISSUE TITLE
Docs are not clear and outdated in places

### ISSUE THREAD

**Issue by eddie-englund** [revolist/revogrid#348]
All of the demos are outdated and don't use the new version 3. I also cannot find a good example of the dependencies that are required with v3. Revolist version, stencil version, and where/how to set this up with webpack!

Yes, I have seen https://revolist.github.io/revogrid/guide/installing.html#webpack-module-import but where should this go, in my webpack conf? Not quite clear to me!

Also, is there any place I can see the themes available in use?

**Comment by revolist** [comment]
Hello, check v4 and https://rv-grid.com
if you find something outdated pls let us know. 
sorry for such a late response.
