### ISSUE TITLE
Scrolling to focused cell not working when using Bootstrap 5

### ISSUE THREAD

**Issue by sven42** [revolist/revogrid#349]
The default behavior seems to be that a focused cell is scrolled into the visible area. E.g. using cursor keys you can navigate quickly throw the table.

This does not work, when using Bootstrap 5 (Tested with 5.1 and 5.2, 5.2 was worse).

In context of https://github.com/revolist/revogrid/issues/344 I discovered, that part of the problem seems to be that some CSS settings are getting normalized by Bootstrap (and most probably by many other CSS-Solutions like Tailwind).

With the work around from https://github.com/revolist/revogrid/issues/344 in place, at least _vertical scrolling_ is working again:

```
revo-grid [hidden] {
    display: initial !important;
}
```

However, I did not manage to find other settings which interfere with revo-grid and need to scroll horizontally with extra event handlers, which has other issues.

**Comment by sven42** [comment]
Hello,

I just discovered that my scrolling issue was caused by a combination of using Bootstrap 5 and updating grid.columns when it was not needed.

So scrolling is working for me with the mentioned work around in #344

**Comment by revolist** [comment]
Marking as fixed.
