### ISSUE TITLE
Custom Filter is error, get TypeError: filter is not a function

### ISSUE THREAD

**Issue by JavaZWT** [revolist/revogrid#353]
Hi,revogrid.
When I use filters of advance-usage, and I get a error:
 Uncaught (in promise) TypeError: filter is not a function

https://revolist.github.io/revogrid/guide/filters.html#advance-usage

![image](https://user-images.githubusercontent.com/23694794/187844198-c2857c99-86ee-4efe-ae78-b02a57add926.png)

**Comment by JavaZWT** [comment]
And I created a  [#PR](https://github.com/revolist/revogrid/pull/354)

**Comment by revolist** [comment]
Hey @JavaZWT 
merged, will come in next release
