### ISSUE TITLE
Select for a single cell

### ISSUE THREAD

**Issue by chrisoprea** [revolist/revogrid#358]
Is it possible to use a @revolist/revogrid-column-select for a single cell rather than the entire column?

Vue 2 / vue-datagrid

Example:
![image](https://user-images.githubusercontent.com/78136650/191695408-e7f73c39-ea29-41ca-a60a-11b8085616e4.png)

**Comment by revolist** [comment]
You can do it but would require to write your own column plugin, this is available in Pro version
