### ISSUE TITLE
Paste into cell editor throws errors

### ISSUE THREAD

**Issue by Error07** [revolist/revogrid#362]
Hello and good job on the Grid overall! Its a really powerful component.
I didnt find any issue for this, so here is a new one.

When you try to paste some value into a cell-texteditor, then you see a error in the console. It seems to have worked tho.
You can also test this on the revogrid main demo: https://revolist.github.io/revogrid/demo/
I pasted some text into the first Column (Name(autosize)), which resulted in this console errorlog:

```
1.a8161c8c.js:1 TypeError: Cannot read properties of null (reading 'rows')
    at ko.htmlParse (1.a8161c8c.js:1:183597)
    at ko.onPaste (1.a8161c8c.js:1:183104)
    at HTMLDocument.<anonymous> (1.a8161c8c.js:1:1582) undefined
```

edit:
that's weird. i dont know what changed, but now the behaviour is a little different. when i double-clicked into the column to edit it, tried to paste, nothing happens. i can paste from outside the editor tho.

edit2: when i copy something from VSCode i get the error message, otherwise i get the behaviour from the first edit and nothing happens.

Keep up the good work!
Greetings
Error07

**Comment by revolist** [comment]
Can not reproduce in v4.
