### ISSUE TITLE
Focus on previous cell

### ISSUE THREAD

**Issue by ArturoWipe** [revolist/revogrid#363]
#### Description:
> As a user, when keying the **"tab + shift"** command shortcut, I want the **focus selector to move to the previous cell**.
This is a common pattern in Excel, Google Sheets, etc.

#### As of now:
- while using the `range=true` setting, using "tab + shift" triggers the selection range to focus on multiple cells from the current row
  - the "shift + right" keys are actually doing the same result
  - I think that we should get rid of this behavior to dedicate the "tab + shift" command shortcut to focus on the previous cell
- while using the `range=false` setting, using "tab + shift" triggers the same behavior as "tab", ie. focus to the next cell

#### Preferred solution:
1. *at bes*t: adding the "tab + shift" to focus to the previous cell, plus get rid of the redundant "tab + shift" behavior when `range=true`
2. *if not possible*: provide the `setCellsFocus` method, offering the developer the benefit of adding its own event listener and making the focus programmatically

----

##### Related issues:
- #274 → _issue closed, but while trying to upgrade the library to the  `"4.2.0-next.8"` release, the `setCellsFocus` method were still not available_
- #208

**Comment by revolist** [comment]
Updated
