### ISSUE TITLE
Svelte demo does not show up out-of-the-box

### ISSUE THREAD

**Issue by piperun** [revolist/revogrid#364]
**Describe the issue**
It's essentially 2 issues at once:
Testing the basic revogrid example for svelte does not work because revogrid relies on:
```
<style>
  main {
    font-family: sans-serif;
    text-align: center;
    height: calc(80vh);
  }
</style>
```

Which is not provided in the basic example (it is in the codesandbox example).
And this in turn causes some headache since ur suppose to copy/paste that `<style>` whenever you want to "box-in" retrogrid component.

**To Reproduce**

https://codesandbox.io/s/revogrid-svelte-latest-forked-41cqom?file=/Grid.svelte

**Comment by MadeByDouglas** [comment]
I also noticed this, well and now the demo doesn't even load in the sandbox, it has an error.
I am new to web dev and revogrid, what did you do to make it work? I tried adding the styles in my svelte file but still doesn't show.

**Comment by revolist** [comment]
https://rv-grid.com/guide/svelte/

fixed v4
