### ISSUE TITLE
Bug: Row grouping is resetted after data source change

### ISSUE THREAD

**Issue by AndreasCaldewei** [revolist/revogrid#365]
The row grouping is reset after a new data source is applied to the grid. Collapsed groups are uncollapsed after the data source change occurs. 

On the demo project set grouping by key, and open a group in the table, after that select a new data source (100 x 100).

I looked at the current implementation of the row-sorting plugin and previously collapsed groups are probably not taken into account. A fix could be that we store each collapsed group inside the store and apply these groups after the data source change.

Should I make a PR for this?

**Comment by revolist** [comment]
We just fixed it, sorry for this long time waiting. This issue was lost in the history.
