### ISSUE TITLE
Add classes if uneven and odd rows for styling

### ISSUE THREAD

**Issue by AtishaGarinMchd** [revolist/revogrid#367]
**Describe the issue**
Data are divs and css selector nthchild for alternate row styling is not a proper solution due to virtual dom and transforms applied
It could be possible to generate selectors based on attributes using data-row applied to cells, but that would be cumbersome

**To Reproduce**
Any doc example.

A more straightforward solution would be appreciated through either: a per table prop pointing to a css-variable / 2 hex values / exposing a css class.

**Comment by revolist** [comment]
You can achieve this multiple ways, I would recommend to go with row classes property and apply it, other option to write your own plugin or use pro plugin v4+

**Comment by revolist** [comment]
Done for Pro version
