### ISSUE TITLE
can we modifie data before exporting a file , in my case before export is not working.

### ISSUE THREAD

**Issue by Jyoti-Khatkar** [revolist/revogrid#369]
**Check if issue exists**
Search the repo and ensure your issue doesn't already exist. If so, it may:
- Have already been fixed in an unreleased version.
- Have been closed without a solution. Please create a new issue instead of commenting on the old one.

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Create a minimal reproduction to illustrate the issue. Here's a [template](https://codesandbox.io/s/revo-grid-vanilla-js-7cq7c) to start you off.

**Comment by revolist** [comment]
You can use https://rv-grid.com/guide/api/clipboard.html as starting point for modification clipboard
