### ISSUE TITLE
Event afteredit is called two times

### ISSUE THREAD

**Issue by Jenvers** [revolist/revogrid#373]
in angular the afteredit event when called to get the details shows me twice the same detail.

This is the code

App component HTML

 <revo-grid [source]="rows" [columns]="columns" theme="material" (afteredit)="onAfterEdit($event)"></revo-grid>

App Component Typescript

  onAfterEdit({ detail }) {
    console.log(detail)
  }
}

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/39636639/207746366-40643066-e59f-47c6-996d-8e20ae4ce9c4.png">

**Comment by revolist** [comment]
No longer valid for v4
