### ISSUE TITLE
Text not selectable on readonly or canFacus (false) grids

### ISSUE THREAD

**Issue by donmb1** [revolist/revogrid#377]
```
<v-grid
      theme="material"
      :source="rows"
      :columns="extendedColumns"
      :resize="true"
      :stretch="true"
      :readonly="true"
      :canFocus="false"
      rowClass="bg-stone-50 z-10"
      :rowSize="40"
      @beforesortingapply="emitSorting"
      @beforeCellFocus="beforeFocus"
    />
```

Unfortunately it is not possible to select any text (and e.g. copy it to clipboard) if a table is in readonly mode or has `canFocus` set to false. This makes it kind of inconvenient for users to interact with data.
As a user I want to select text via Cursor and copy it to clipboard.
Is there any workaround for this?

**Comment by revolist** [comment]
Should no longer be the problem in version 4
