### ISSUE TITLE
Editor as Vue component example is broken

### ISSUE THREAD

**Issue by glad4enkonm** [revolist/revogrid#381]
![image](https://user-images.githubusercontent.com/11142000/213740205-5da5de10-9fbf-4c4e-ad6e-85ae92a2869f.png)

It looks like the "Editor as Vue component" example is broken.

Steps to reproduce 
- open the example https://revolist.github.io/revogrid/guide/framework.vue.editor.html
- click on any cell
- expected to be an error (see the attached image)

**Comment by awacode21** [comment]
i can confirm, i am experiencing the same problem. it is still not working

**Comment by revolist** [comment]
4+ version is there, should be working ok.
