### ISSUE TITLE
Typescript errors on multiple files

### ISSUE THREAD

**Issue by florentsuc** [revolist/revogrid#382]
Starting from typescript **4.8.X**, multiple typescript definition files are not compiling anymore.

You can reproduce the bug on the lib by updating typescript to **4.8.X.** 

The following files are not compiling anymore:
```
- @revolist/revogrid/dist/types/store/dataSource/data.store.d.ts:72:71 -
- @revolist/revogrid/dist/types/plugins/trimmed/trimmed.plugin.d.ts:9:120 
```

Error examples: 
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/1432929/214887636-aa662311-15f3-4fbe-8fb4-6cb7fd1143bd.png">

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/1432929/214889259-0550b2fc-02c8-46b2-a9e7-4da0a8e00b12.png">

The problem is that typescript version dependency is prefixed by `^` in `package.json` so if you run `npm update` it will update typescript to **4.9.X** and raise the issue.

Thank you :) 

**Edit:**  If anyone is facing the same issue, I disabled the errors by adding this in the tsconfig.json:

```
"compilerOptions": {
    "skipLibCheck": true
}
```

**Comment by revolist** [comment]
Can not reproduce anymore on 4+
