### ISSUE TITLE
Clipboard with JSON Support and Advanced Objects

### ISSUE THREAD

**Issue by eddie-englund** [revolist/revogrid#383]
I have an issue where some values I can only get some in objects, in this case, a value and a currency.

```json
"metaAmount": { "value": 100, "cy": "EUR" }
```

And so to display currency in its own column I must do a create element

```js
    cellTemplate: (createElement, { model, prop }) => createElement('p', {  }, model[prop].cy)
```

However, the issue now is that if you attempt to copy this value you will get the "props" value which is an object and then the copy value becomes [object Object].

I'd like to be able to alter what actually becomes copied.

Example of the issue (copy the "bar" value in the second column) https://codesandbox.io/s/revo-grid-vanilla-js-forked-w1ndqq

Cheers

**Comment by revolist** [comment]
We have this as part of Pro version also you could overwrite all events starting from v4. Please check https://rv-grid.com/guide/api/clipboard.html

**Comment by revolist** [comment]
**Objective**: Enable clipboard functionality to support JSON and advanced objects for copying and pasting complex data structures.

**Description**: Develop clipboard functionality that allows copying and pasting of JSON and complex data structures between grids and applications.

**Acceptance Criteria**:
- **Clipboard Functionality**: Support JSON and advanced objects.
- **Data Handling**: Ensure accurate data transfer and integrity.
- **Documentation**: Provide examples and usage instructions.

**Comment by revolist** [comment]
Done
