### ISSUE TITLE
TypeError: o2.sourceLookup[i2] is undefined 

### ISSUE THREAD

**Issue by glad4enkonm** [revolist/revogrid#384]
I'm using revo-grid for vue3 and need a  Select data type. According to  [this docs](https://revolist.github.io/revogrid/guide/column.types.html#select) I 

1. instilled  `npm i @revolist/revogrid-column-select`
2. imported `import SelectTypePlugin from "@revolist/revogrid-column-select";`
3. created a data element `summaryGridSelectPlugin: { 'select': new SelectTypePlugin() },`
4. Defined columns 
```
columnsSummary: [
...
{
   "prop":"package",
   "name":"Package",
   "size":110,
   "columnType":"select",
   "labelKey":"label",
   "valueKey":"value",
   "source":[
      {
         "label":"According",
         "value":"a"
      },
      {
         "label":"Over",
         "value":"b"
      },
      {
         "label":"Source",
         "value":"s"
      }
   ]
},

...
      ],
```
5. Defined rows 
```
rowsSummary: [{
        name: "1",
        details: "Item 1",
        package: "package 1"
      }],
```
7. Created a grid `<v-grid readonly="false" theme="compact" :source="rowsSummary" :columns="columnsSummary" id="summary-grid" :column-types="summaryGridSelectPlugin" />`

### Getting this error message
in browser console, the table headers are shown but no rows

```
TypeError: o2.sourceLookup[i2] is undefined
    i main.js:1
    customRenderer columnService.js:539
    getCellRenderer revogr-data2.js:129
    render revogr-data2.js:109
    callRender index.js:1789
    updateComponent index.js:1727
    node_modules @revolist_vue3-datagrid.js:5833
    then index.js:1938
    dispatchHooks index.js:1708
```

**Comment by revolist** [comment]
We updated select type to the latest version 4+
