### ISSUE TITLE
Failed to fetch dynamically imported module: https://y0g9y3-3001.sse.codesandbox.io/node_modules/.vite/deps/duet-date-picker.entry.js 

### ISSUE THREAD

**Issue by Jyoti-Khatkar** [revolist/revogrid#386]
ColumnType Select and DatePicker give error this error,

Can anyone help me to resolve this error, in cli its working fine but the error comes into vite-vue project

**Comment by revolist** [comment]
Can't reproduce it anymore, try v4 https://rv-grid.com
