### ISSUE TITLE
React component is getting mounted newly on cell click with using react adaptor mentioned in docs

### ISSUE THREAD

**Issue by tsp1998** [revolist/revogrid#388]
**Describe the issue**
- While using react with Revogrid, I am facing some challenges
- I used the adaptor snippets mentioned in docs at https://revolist.github.io/revogrid/guide/framework.react.component.html
- Each time when I click on cell, it is unmounting at mounting react component due to which I am not able to proceed with component operations. in this case selecting option for select component.
- tries couple of other ways to tackle this issue such as passing store at root level of Revogrid which is not giving state inside cell component as it needs me to pass store for each cell individually which has performance issues as I am using millions of cells.
- Another thing tries is skip unmounting in adaptor but not able to communicate latest data with component in this case.

**To Reproduce**
please visit: https://codesandbox.io/s/revogrid-react-42tw64?file=/src/App.tsx

**Comment by revolist** [comment]
React version was updated with version 4+. New editor/component renderers.
