### ISSUE TITLE
Ctrl-V not working while in edition

### ISSUE THREAD

**Issue by aless673** [revolist/revogrid#390]
Cut and Copy work good but Paste works only while focusing, not while editing 

![image](https://user-images.githubusercontent.com/6001339/221204196-d825785f-423c-4f56-b085-1062ad8abe21.png)

You can reproduce this on any demo : https://revolist.github.io/revogrid/demo/

Is there any workaround for this ?

**Comment by paramula** [comment]
same issue

**Comment by AlexECX** [comment]
it's not too much of a problem when you want to paste over the cell, but when you need to add a block of the same text to 20 cells already containing non-identical text it's time-consuming

**Comment by revolist** [comment]
Can not reproduce on 4+
