### ISSUE TITLE
cellCompare / sorting does not work if a cellTemplate is present

### ISSUE THREAD

**Issue by eddie-englund** [revolist/revogrid#396]
When sorting with cellCompare (or just any sorting i.e default sort), then the row you select doesn't move as it's supposed to but rather all the other rows move which are not using cellTemplate with VGridVueTemplate.

With cellTemplate (note that all the rows around it are also using cellTemplates)

https://user-images.githubusercontent.com/16852656/235902165-afae971e-56c3-4853-ad88-49651a590456.mov

Without cellTemplate

https://user-images.githubusercontent.com/16852656/235902183-a1e0db6a-ad3f-4186-9529-a18b6f7d56a4.mov

Reproduce: https://codesandbox.io/s/determined-zeh-854ibx?file=/src/App.vue

**Comment by os-tohe** [comment]
I am having the same problem. Is there any way to fix this?

**Comment by eddie-englund** [comment]
I haven't been able to figure out a solution to this so we had to do the sorting ourselves on the back-end and hackily get access to the click event on the headers.

Would really like this fixed!

**Comment by revolist** [comment]
fix: https://github.com/revolist/vue3-datagrid/commit/ea33005b0eceaa2ed5c47dc1b20f43a50ccbc70e
