### ISSUE TITLE
Enhancement: Quick select specific column in all rows

### ISSUE THREAD

**Issue by eddie-englund** [revolist/revogrid#397]
Currently (as far as I can tell, if there is please let me know how to do it with the vue adapter) there is no way to select a column to select that specific column in all rows which would be very useful for copying.

In excel you can do this by pressing the header

<img width="698" alt="image" src="https://user-images.githubusercontent.com/16852656/235921114-28fce2d6-18fd-488a-acf8-a7634a1f16e2.png">

**Comment by revolist** [comment]
You can have a plugin which would do this you just have to apply Select all to selection.store. We have it as a Pro feature in v4+
