### ISSUE TITLE
Row grouping - how it works?

### ISSUE THREAD

**Issue by monoidor** [revolist/revogrid#398]
Hi, thanks for the solution!

The [Key Features](https://github.com/revolist/revogrid#key-features) says to support Column grouping and Row grouping.
There is an [example](https://revolist.github.io/revogrid/guide/column.grouping.html#grouping-stacked-columns) for an Column grouping, but I couldn't find one for an Row grouping.

Where can I find an example for a Row grouping?

Tell me, please, can I make a table like this with a grouping of rows?
![table](https://github.com/revolist/revogrid/assets/24909852/86fe13fb-0425-4452-bf49-c6a9a49ead54)

**Comment by revolist** [comment]
It's not grouping column, it's merging cells you can do it with Pro feature.
