### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'focused' / 'clearAutoFillSelection')

### ISSUE THREAD

**Issue by os-tohe** [revolist/revogrid#403]
**Description**
In Vue3, when I move to the page using router where the VGrid component is and hover over it, it starts throwing error messages. When I hover over it it throws this error:
```
index.js:3204 TypeError: Cannot read properties of undefined (reading 'focused')
at proxyCustomElement.readonly.onMouseMove (revogr-overlay-selection2.js:476:18)
at HTMLDocument.<anonymous> (index.js:3007:35) undefined
```
If I click anywhere on screen it throws this error:
```
index.js:3204 TypeError: Cannot read properties of null (reading 'clearAutoFillSelection')
at proxyCustomElement.readonly.onMouseOut (revogr-overlay-selection2.js:482:16)
at HTMLDocument.<anonymous> (index.js:3007:35) undefined
```
The error persists until I refresh the page. If I just move to other page, it still throws the error whenever I move the mouse. The problem does not occur if the VGrid is on the initial page, for example if I move to the page by changing the url.

**Console log**
![RevoGrid error](https://github.com/revolist/revogrid/assets/126565419/fd4bfbb6-5003-49d4-ae33-884df88bd85a)

**Comment by os-tohe** [comment]
I was able to work around this issue by adding `v-if="show"` to VGrid, setting it to `false` by default and enabling it after 1 millisecond:
```
setTimeout(() => {
  show.value = true
}, 1)
```

**Comment by m2a2x** [comment]
Hello, is there a way you could provide https://codesandbox.io/s/revo-grid-vue3-thry7 example with this problem?
It seems element is missing on the init stage.

Thank you!

**Comment by os-tohe** [comment]
I am unable to reproduce the error now. I have drastically modified my code, so probably something I did has fixed it.
