### ISSUE TITLE
How to display specific columns?

### ISSUE THREAD

**Issue by silphonix** [revolist/revogrid#404]
Hi, i have lots of data with different names. I need to display two columns, "terms" and "synonyms" but let the user determine with two selectors which column is "terms" which one is "synonyms" and to hide everything else.

Is there a built in way to handle this ? like hide all columns except the first two, or have a check of columns ? because the other way around this i can think of is to manipulate either the data, or to just add a display none in the props of every column except the first two, and have an event when the user changes with a select which column is to remove the display none and re-asign it to the previous column.

Thanks !

**Comment by revolist** [comment]
The easiest to write your own plugin to control it or manipulate data.
