### ISSUE TITLE
How does the versioning and the release work?

### ISSUE THREAD

**Issue by JakobMiksch** [revolist/revogrid#414]
On npm the version [3.6.14](https://www.npmjs.com/package/@revolist/revogrid/v/3.6.14) is released. But I cannot find any tag or code in this repository that references to this tag. 
Also the releases on GitHub are not in sync with the releases on npm. 

Is this on purpose, how is does the current release procedure work?

**Comment by m2a2x** [comment]
Hello @JakobMiksch 
The release procedure for this project involves two types of version releases. For minor updates, such as small library updates, we directly release those versions on npm without generating GitHub automated builds. As a result, you may not find specific tags or code references for these intermediate versions in the GitHub repository.

However, for major versions, we follow a different approach. All major releases are made through GitHub, which includes creating version tags and GitHub releases to properly document and track the changes made in that version.

This release strategy allows us to streamline the process for smaller updates while still providing proper documentation and version management for significant changes.

**Comment by JakobMiksch** [comment]
@m2a2x thanks for your detailed explanation. This is very helpful.
