### ISSUE TITLE
Version 3.6.17 is not available in the npm registry

### ISSUE THREAD

**Issue by Stanislavsky69** [revolist/revogrid#415]
Hello! Please add version 3.6.17 to the registry, thank you!

**Comment by Stanislavsky69** [comment]
@JakobMiksch If I understood correctly, then I can get the latest version only by downloading the repository?

**Comment by JakobMiksch** [comment]
I don't know. I guess only the maintainers can answer that.

**Comment by revolist** [comment]
4+ is the latest
