### ISSUE TITLE
"Next" version 4 - when to expect? Impact at current bug list?

### ISSUE THREAD

**Issue by awacode21** [revolist/revogrid#418]
This is not really a bug, but as the repo does not provide a discussions area where someone can ask questions i need to go this way, sorry about that.

I would like to ask when to expect the "next" version of revogrid. Version 4? Seems like there is a branch and people are working on it.

On current version there is quite a bunch of bugs, most of the 1-2 years old without any feedback, any comment, no one working on then. Also things like "Javascript maximum call stack size exceeded" so really major things.
The question is will the new version 4, the "next" one.. fix those bugs? Does it handle the current bug list at all? Or is it just adding some features?

Also the current documentation is unclear in some point and examples simply are broken.

I am currently evaluating if revogrid could be an option for one of my customers,  but with current version it seems to be not maintained nor stable enough and i ask myself if it makes sense to expect and wait for the new version or to choose something else.

Any feedback is appreciated.

**Comment by stewartadam** [comment]
+1 to doc updates, what just bit me is 'npm install @revolist/revo-grid' (per v3 docs) is pulling down version v4.x and they don't behave entirely similarly.

**Comment by revolist** [comment]
Hello everyone, apologies for the oversight. Indeed, our documentation had inaccuracies, but as of now, npm fetches the latest published version.

We're targeting the release of the new version either by the end of this month or early next month. Our focus has been primarily on our new product, Revosheets. It's built entirely on the RevoGrid library, which continues to grow and enhance in tandem. Thank you for your patience and understanding. 🙏🚀📚

A list of changes will be huge, but mostly typings updates which will be breaking.
But overall we increased functionality around all methods, passed more methods

**Comment by Yiidiir** [comment]
@revolist Good to hear back from you!

Do you know if RevoGrid v4 (not Revosheets) is going to be open-source like the current version or there will be some kind of freemium model community/premium like those other vue/react modules?

**Comment by revolist** [comment]
Hello @Yiidiir 

It's going to be open-source,

But we are doing to add a separate premium library and code examples which would explain how to make advance things like merging cells, history, advance filtering, etc. Hence we need help to continue developing grid and improving it for everyone.

At this moment we are brainstorming how to introduce it.

Thanks for the interest!

**Comment by revolist** [comment]
Just released, sorry for such a long delay. It was a big challenge to support it across all zoo of frameworks. We'll have to switch to mono repo to simplify the process.
