### ISSUE TITLE
Cannot find name ColumnService - during build process in Typescript project

### ISSUE THREAD

**Issue by verena-ifx** [revolist/revogrid#420]
TypeScript: ../../node_modules/@revolist/revogrid/dist/types/components.d.ts:276:26
Cannot find name 'ColumnService'. Did you mean 'ColumnSource'?

I get this error when building my Stencil project. I have followed the installation steps. I ran npm install and imported the module as described. Anyone else came across this behavior?

**Comment by revolist** [comment]
Can not  reproduce. Still required?
