### ISSUE TITLE
Auto size feature is not working

### ISSUE THREAD

**Issue by dmitri-vlasov** [revolist/revogrid#423]
First, thanks for great library!

**Describe the issue**
Auto size feature is not working - applying any of the parameters listed here https://revolist.github.io/revogrid/guide/autosize.html#column-autosize not affecting the column width - the text is cut and hidden and column width is not changed according to text. 

Please see here: https://codesandbox.io/s/revo-grid-vanilla-js-forked-htt7mj?file=/src/index.js

**To Reproduce**

1. Create a revs-grid and add a test data with long text in cells;
2. add any of parameters like from here like :

```
grid.autoSizeColumn = {
  mode: "autoSizeAll"
};
```

See an example: https://codesandbox.io/s/revo-grid-vanilla-js-forked-htt7mj?file=/src/index.js:617-665

**Comment by dmitri-vlasov** [comment]
For all who stuck with the same. It worked with the following config:

`        grid.autoSizeColumn = {
            mode: 'autoSizeAll',
            allColumns: true
        };`
        
Closing the issue, nothing to fix actually.

**Comment by dmitri-vlasov** [comment]
Forgot to mention - I also added `grid.rowHeaders` to make it work.

**Comment by logan-lopez-quinsite** [comment]
Just going to leave this here in case anyone runs into it...

I was having an issue getting the auto sizing to work, and it ended up being something really simple that I just misread in the docs.

Make sure the propery is called `autoSizeColumn` not `autoSizeColumns`.

Completely on me for using the wrong property, but I figured I would share
