### ISSUE TITLE
Revogrid new component for cellTemplate 

### ISSUE THREAD

**Issue by jfloww** [revolist/revogrid#424]
const myVue = Vue.component('my-component', {
  props: ['rowIndex'],
  data: function () {
    return {
      count: 0
    }
  },
  methods: {
    iAmClicked(e: any) {
      this.count++
    }
  },
  template: '<button v-on:click="iAmClicked">You clicked me {{ count }} times.</button>'
})
const columns = [
  { name: 'DELIVERY NO', prop: 'deliveryNumber', size: 150 },
  { name: 'DETAIL', cellTemplate: TableContainer.VGridVueTemplate(myVue), size: 200 }
]

I want to test for cell onclick action. but have several errors. I have stucked on this error for 3days.. 
There are two error in my console.
1. Property 'component' does not exist on type 'typeof import("D:/Projects/.../node_modules/vue/dist/vue")'.
2. Property 'count' does not exist on type '{ iAmClicked(e: any): void; }'.

Do you guys have any solution for these errors?
Thanks in advance.

**Comment by jfloww** [comment]
Solved the problem

**Comment by Karan9615-off** [comment]
@m2a2x How can we access the source ( rows ) in the component passed as columnTemplate ?
```javascript
 columnTemplate: VGridVueTemplate(CheckboxTemplateCol),
```
