### ISSUE TITLE
rollup build conflict

### ISSUE THREAD

**Issue by blackPeppper** [revolist/revogrid#433]
**Describe the issue**
there is a lot of issues but this one is the most important one

while i was in the dev mode nothing happening but when i build i get this error
"/@PURE/"  in "node_modules/.pnpm/@revolist+revogrid@4.7.0-next.4/node_modules/@revolist/revogrid/dist/esm/index-dec89046.js" contains an annotation that Rollup  cannot interpret due to the position of the comment. The comment will be removed to avoid issues. ✓ 131 modules transformed.

revo gird make a somehow lazy bundling by it self
i am using react env when i treied to switch to vite@4.5.0
i did't get the err but the is same  issue

build files 
![image](https://github.com/revolist/revogrid/assets/93441520/b55b1c67-8fbc-4c08-838d-7a0944428e88)
dev mode
![image](https://github.com/revolist/revogrid/assets/93441520/bbcc1d8e-122d-4821-b25a-6e500dac90e4)
build mode
![image](https://github.com/revolist/revogrid/assets/93441520/c26b4ea4-9e84-4dd4-88ce-2558e9a4fe5f)
![image](https://github.com/revolist/revogrid/assets/93441520/3e96e2a1-743c-4d9c-bcef-400b70a14e89)
![image](https://github.com/revolist/revogrid/assets/93441520/2168d6c1-e65e-4c21-bfef-d864c37a1f11)
after these [instructions](https://github.com/revolist/revogrid/blob/master/docs/custom.element.md)
![image](https://github.com/revolist/revogrid/assets/93441520/340674db-3da8-48c7-8f0c-49d8d132e5a1)
![image](https://github.com/revolist/revogrid/assets/93441520/7a83ce8f-99a2-4daf-b4be-c9e5bed1eedf)
![image](https://github.com/revolist/revogrid/assets/93441520/42a564eb-cfa8-42c4-a258-edef84e7c25a)

**To Reproduce**
it is a company project i can't share it

**Comment by revolist** [comment]
Can not reproduce anymore
