### ISSUE TITLE
Select All elements in table

### ISSUE THREAD

**Issue by AndreFulghesu** [revolist/revogrid#436]
Hi,
currently i'm using vue3-datagrid 3.2.17 ad i see whether I focus on a cell and I click Ctrl + a the whole page is selected instead of the elements of the table. This feature for example is present in the vue3-datagrid 3.0.97 but I'm not using this one because the sort doesn't work giving this error "TypeError: Cannot read properties of undefined (reading:'bind'). 
I'm using Vue 3.3.11 with Vite 5.0.10. 
in the vue3-datagrid 3.0.97 i've see that if I don't import in the main.js 'defineCustomElements' from loader the select all cells feature is being lost, but adding the same in the 3.2.17 doesn't change anything. Am I doing something wrong?
The grid is correctly imported in the component and I'm not using some kind of templates inside cells.
Thanks a lot

**Comment by revolist** [comment]
Should be working in the latest
