### ISSUE TITLE
@revolist/revogrid-column-numeral fails with NumberColumnType is not a constructor

### ISSUE THREAD

**Issue by rmoskal** [revolist/revogrid#453]
You can see a very minimal example reproduced here:

https://svelte.dev/repl/b1da73b1d8cb4baba06c2453cbd45122?version=3.55.1

![image](https://user-images.githubusercontent.com/562035/223779557-4e9dfef1-4cf9-4cfc-beba-0baa78fea68b.png)

**Comment by revolist** [comment]
Please try to reproduce on the latest version. 
There is no issue on our side.
https://stackblitz.com/edit/vitejs-vite-dvilmw?file=README.md
Sandbox to start ^
