### ISSUE TITLE
Date Input Closes Automatically When Changing Month or Year (vue 3 version)

### ISSUE THREAD

**Issue by TheoDeberles** [revolist/revogrid#460]
Description :

I am experiencing an issue with the date input in a Vue.js project using the @revolist/revogrid-column-date and @revolist/vue3-datagrid packages. When setting the columnType property to date, the date picker input appears as expected. However, when I try to change the year or month, the input closes automatically, preventing me from selecting a date.

Package.json :
```
{
  "name": "test-excel",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@revolist/revogrid-column-date": "^2.0.0",
    "@revolist/vue3-datagrid": "^4.8.1",
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "vite": "^5.3.1"
  }
}
```
Steps to Reproduce:

Set up a project with the above package.json.
Configure a table column with columnType set to date.
Click on the date cell to open the date picker input.
Try to change the year or month in the date picker.
Expected Behavior:
The date picker should remain open, allowing the user to change the year or month and select a date.

Actual Behavior:
The date picker input closes automatically when attempting to change the year or month, preventing date selection.

My actual test component: 

```
<template>
  <v-grid
      theme="compact"
      :source="rows"
      :columns="columns"
      :columnTypes="columnTypes"
  />
</template>

<script>
import VGrid from "@revolist/vue3-datagrid";
import Plugin from "@revolist/revogrid-column-date";
export default {
  name: "excel-2",
  data() {
    return {
      columns: [
        {
          name: "Birth",
          prop: "birthdate",
          columnType: "date",
          size: 150,
        },
        {
          prop: "name",
          name: "First",
        },
      ],
      rows: [
        {
          birthdate: "2022-08-24",
          name: "1",
          details: "Item 2",
        },
        {
          birthdate: "2022-08-24",
          name: "2",
          details: "Item 2",
        },
      ],
      columnTypes: { date: new Plugin() },
    };
  },
  components: {
    VGrid,
  },
};
</script>

<style>
#app {
  height: 700px;
  width: 500px;
}
revo-grid {
  height: 100%;
}
</style>
```
Thank you for your assistance in resolving this issue.

**Comment by TheoDeberles** [comment]
![Enregistrementdelcran2024-07-16170929-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/bf7274c3-97a2-4032-baba-aa89bc2f952e)

**Comment by revolist** [comment]
Hello @TheoDeberles,

Thank you for your interest in our grid and for providing a detailed explanation of the issue.

It seems like you are currently using version `2.0.0` of `@revolist/revogrid-column-date`. The latest version is `2.0.19`, which includes several bug fixes and improvements that might resolve the issue you're experiencing.

I have created a working example for you, which demonstrates the date picker functioning correctly: [Working Example](https://rv-grid.com/demo/js/js.date.html).

To update your project, please ensure you are using the latest version of the `@revolist/revogrid-column-date` package. You can do this by updating your `package.json` and reinstalling the dependencies:

1. Update `package.json`:
   ```json
   {
     "dependencies": {
       "@revolist/revogrid-column-date": "^2.0.19",
       "@revolist/vue3-datagrid": "^4.8.1",
     },
   }
   ```

2. Reinstall dependencies:
   ```sh
   rm -rf node_modules package-lock.json
   npm install
   ```

3. Verify your component setup:
   Ensure that your component setup matches the latest configurations:

   ```vue
   <template>
     <v-grid
       theme="compact"
       :source="rows"
       :columns="columns"
       :columnTypes="columnTypes"
     />
   </template>

   <script>
   import VGrid from "@revolist/vue3-datagrid";
   import Plugin from "@revolist/revogrid-column-date";

   export default {
     name: "excel-2",
     data() {
       return {
         columns: [
           {
             name: "Birth",
             prop: "birthdate",
             columnType: "date",
             size: 150,
           },
           {
             prop: "name",
             name: "First",
           },
         ],
         rows: [
           {
             birthdate: "2022-08-24",
             name: "1",
             details: "Item 2",
           },
           {
             birthdate: "2022-08-24",
             name: "2",
             details: "Item 2",
           },
         ],
         columnTypes: { date: new Plugin() },
       };
     },
     components: {
       VGrid,
     },
   };
   </script>
   ```

Please let me know if you encounter any further issues or if the problem persists.

Best regards,
Revolist Team
