### ISSUE TITLE
Bug: Excel-Like row editing with Tab does not work in v4.8.2

### ISSUE THREAD

**Issue by sven42** [revolist/revogrid#471]
Hello,

first I want to thank you for releasing a new version with so many improvements.

However, when migrating from the latest v3.7 to v4.8.2 I discovered that during cell-editing the Tab-Key is behaving differently
- v3: Commit changes and move to next cell 
  - so this enables fast excel like editing of row values
- v4: Focus is set to some other component

**To Reproduce**
Compare the demo for v3 (https://revolist.github.io/revogrid/demo/) with the one for v4 (https://rv-grid.com/demo/)
1. Go to cell A1
2. enter a number
3. press Tab-Key

Best regards,
  Sven

**Comment by m2a2x** [comment]
@sven42 It's done.
