### ISSUE TITLE
Table resize not working properly if cellTemplate is set [Angular]

### ISSUE THREAD

**Issue by Thoemmy** [revolist/revogrid#474]
**Describe the issue**
If you set a cellTemplate and also set in the html element ```<revo-grid>``` the property ```[resize]="true"```.
Then the resizing of the columns is not working properly.

htmlcode:
```html
<revo-grid
    style="height: 200px; width: 300px"
    [columns]="columns"
    [source]="source"
    [resize]="true">
</revo-grid>
```

Current:
<img width="350" alt="Bildschirmfoto 2024-07-19 um 19 06 40" src="https://github.com/user-attachments/assets/4dd73d8e-ebca-45f4-b204-5e90200391cf">

Expected:
<img width="350" alt="Bildschirmfoto 2024-07-19 um 19 10 01" src="https://github.com/user-attachments/assets/aca5efd4-18d8-4671-8f71-ff65b2fc96bd">

**Example To Reproduce**
[Code Sandbox Example](https://codesandbox.io/p/sandbox/table-resize-not-working-properly-if-celltemplate-is-set-angular-4l8pfg)

**Comment by revolist** [comment]
Hello @Thoemmy 
This is how I see this:

<img width="1267" alt="Screenshot 2024-07-20 at 12 33 46 AM" src="https://github.com/user-attachments/assets/5d6422ba-7ac0-4e22-a728-741acd627c05">

Probably there is something else you've done?

**Comment by Thoemmy** [comment]
You opened the sandbox ive created?
Cause the screenshot ive took are from the sandbox?
Is sandbox causing some issues? 
Ive also cloned the repo of angular-datagrid and revogrid to test some cases to help you out

**Comment by revolist** [comment]
I tried directly from your sandbox with no luck. 
Also tried locally with clean angular installation. 
If you get time please send me your browser info too.

**Comment by Thoemmy** [comment]
Oh i saw that i accidentally changed the sandbox example, i reverted my changes to the original issue state. Sorry for that!

The code should look like this:
<img width="838" alt="Bildschirmfoto 2024-07-20 um 23 23 55" src="https://github.com/user-attachments/assets/5ff89be1-7510-482e-8aad-bc7c1d11213d">

This issue is occurring on chrome and safari based browsers

My browser info:
Brave Browser: [Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)](https://brave.com/latest/)
Safari: Version 17.3 (19617.2.4.11.8)

**Comment by revolist** [comment]
I am trying to reproduce your issue on the given sandbox with no luck.
I see exactly same code you've posted above.

Could you see this right now on the sandbox?

**Comment by Thoemmy** [comment]
I opened this example now on a different pc and i have the same issue here.
https://codesandbox.io/p/sandbox/table-resize-not-working-properly-if-celltemplate-is-set-angular-4l8pfg

![image](https://github.com/user-attachments/assets/e64c4d93-45bd-4e9d-b805-7aa979cd01d8)

**Comment by revolist** [comment]
@Thoemmy 
I've been able to reproduce your issue
Gladly it seems not reproducible on the newer version.
Could I ask you to upgrade your sandbox to 4.8.12+ and try again?

https://codesandbox.io/p/sandbox/practical-dirac-864l3r

there is a copy of your sandbox with the latest version

**Comment by Thoemmy** [comment]
@revolist 
Yep the issue is gone in the newer version.
Thank you for help :)

**Comment by revolist** [comment]
> @revolist 
> 
> Yep the issue is gone in the newer version.
> 
> Thank you for help :)

Thank you for checking!
