### ISSUE TITLE
Remove Console.log in projects/angular-datagrid/src/lib/renderer.ts

### ISSUE THREAD

**Issue by Thoemmy** [revolist/revogrid#481]
**Describe the issue**
Remove console.log in angular-datagrid [projects/angular-datagrid/src/lib/renderer.ts](https://github.com/revolist/angular-datagrid/blob/a34f999199907f812451e16f0b86de0583c7295a/projects/angular-datagrid/src/lib/renderer.ts#L48)

**Comment by revolist** [comment]
Done
https://github.com/revolist/angular-datagrid/commit/a774290e3c93231a880e4a830009b00fb3abce6e
