### ISSUE TITLE
Can't set additional properties for date column

### ISSUE THREAD

**Issue by majkelwork** [revolist/revogrid#483]
**Check if issue exists**
Not exists, in version revogrid version 2 is working

**Describe the issue**
I can't add additional properties to the date column. Added values are not displayed and the default calendar is shown.

**To Reproduce**
[Sandbox](https://codesandbox.io/p/sandbox/vue-grid-date-plugin-forked-xx6rg2?file=%2Fsrc%2FApp.vue)

**Comment by revolist** [comment]
https://github.com/revolist/revogrid-column-date/commit/17304b4becf8b6b3bec2a6b5b98b8b366a6797fd

**Comment by revolist** [comment]
@majkelwork there was an issue with property passage in datepicker after unification of types and advance data in editors. We've fixed it asap for you
https://codesandbox.io/p/sandbox/rg-date-column-localization-vue-2-nnd8w3

**Comment by majkelwork** [comment]
@revolist Thank you, everything works. Please change codesandbox privacy settings because no one can view it
