### ISSUE TITLE
button classname "reset" leads to issues due to CSS framework integrations

### ISSUE THREAD

**Issue by Thoemmy** [revolist/revogrid#486]
Hi, currently i have following issue as you can see in the screenshot.
The action button has a class assigned called reset which leads to css spillovers cause the css ramework i am using also includes a class reset.

Also this "reset" css class from revogrid do not have a styling.

Is it possible to rename it? or event to remove it?

![image](https://github.com/user-attachments/assets/016f654a-797c-4df9-9dfe-8efff5712cb7)

**Comment by revolist** [comment]
@Thoemmy ty for the update. This is very minor thing but you could make a PR we'll merge it for the next version.

**Comment by Thoemmy** [comment]
Yes for sure! :)
How can i contribute?
I forked the project and made the update.

Do you have any rules e.g. to contribute?

**Comment by revolist** [comment]
Yes, it's simple:

https://rv-grid.com/guide/CONTRIBUTING.html#Creating-a-Pull-Request
Make sure everything is working as expected and there is no dependencies on it

**Comment by Thoemmy** [comment]
I saw that you labled the issue as feature, so should i revert the PR and recommit the changes as feat?

**Comment by revolist** [comment]
Hey @Thoemmy no worries, it's purely informational.
Ty for the update!

**Comment by revolist** [comment]
Also next time put #486 in commit message, it would appear on the issue itself too
