### ISSUE TITLE
components.d.ts no import BasePlugin

### ISSUE THREAD

**Issue by War-helsink** [revolist/revogrid#517]
**Problem**
Problem with components.d.ts typing when running revogrid in stenciljs project, BasePlugin class not found.

This problem appeared from 4.8.14 to the current 4.8.17, this problem is not present in 4.8.13.

```js
TypeScript: node_modules/@revolist/revogrid/dist/types/components.d.ts:185:28
Cannot find name 'BasePlugin'.
*/
"plugins": (typeof BasePlugin)[];
/**
```
**To Reproduce**
[template](https://codesandbox.io/p/devbox/frosty-wave-49rvsx)

**Local solution**
add BasePlugin import
to node_modules/@revolist/revogrid/dist/types/components.d.ts
 - Add: import { BasePlugin } from "./plugins/base.plugin";

**Comment by revolist** [comment]
Hello @War-helsink 
We are investigating it in priority

Thanks for the update

**Comment by m2a2x** [comment]
Hi! There is a small example
https://rv-grid.com/guide/stencil

**Comment by War-helsink** [comment]
Hi, wow, thank you very much.
