### ISSUE TITLE
Scroll on keyboard selection

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#52]
Hi! Awesome library!!

Would be great if you could support scroll on ARROW_DOWN, ARROW_UP, ARROW_LEFT & ARROW_RIGHT when necessary.

**Comment by revolist** [comment]
Yes, we have this in plans (https://github.com/revolist/revogrid/projects/1#card-42766717), should be done after copy paste feature added.

**Comment by revolist** [comment]
added in 7e1b346

**Comment by navinsaini** [comment]
Keyboard focus scrolling not working. What is the code to work for it.

This is HTML code
`<revo-grid [source]="rows" [columns]="columns" [readonly]="true" [resize]="true" theme="material"></revo-grid>
`

This is typescript code
```
this.columns = [];
    for (var i = 0; i < Fields.length; i++) {
      if (Fields[i].Name !== 'NOTE_TEXT') {
        this.columns.push({
          name: Fields[i].Name,
          prop: Fields[i].Name,
          cellTemplate: (createElement: any, props: any) => {
            return createElement('div', {
              onclick: (event: any) => {
                event.stopPropagation();
              },
              onDblclick: (event: any) => {
                event.stopPropagation();
              }
            }, props.model[props.prop] || '');
          }
        })
      }
    };
    this.rows = Documents;
```
@revolist @kas84  Can you help me here?

**Comment by navinsaini** [comment]
And is there any rowClickEvent?

**Comment by revolist** [comment]
The easiest is to put it on cell and listen from there, but you can override row anytime with beforerowrender event.
