### ISSUE TITLE
Enter data on tab

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#53]
Would be great if you could enter data on tab, so that if you want to enter data from left to right, you easily can.

**Comment by revolist** [comment]
@kas84  Thank you for suggestion! 

Our focus was to duplicate user experience for users from excel.
If you press tab during edit it should work as cancel  and bring your focus to the next cell. Let me know if this is right what you were referring to.

**Comment by kas84** [comment]
At least on excel for mac, you can enter data and tap on "tab" key and the data is not canceled but entered.

Same thing for google sheets.

**Comment by kas84** [comment]
On Excel you can also enter data by tapping arrow keys to go to the next cell. Is that something you'd like too? I think it's handy for entering data fast.

**Comment by kas84** [comment]
@revolist have you checked this out?

**Comment by revolist** [comment]
@kas84 I'm taking expiration from google sheets a lot, they have quite huge ux experience.
It's not a very good idea to save on arrow keys.
According Tab issue you are quite right, we have to bring it just left. I'll think about in during the weekend.

**Comment by kas84** [comment]
That's great!
Google sheets actually does the arrow keys too.

I'm sure it's not quite easy, though, and if not implemented right can have bad UX.

![Grabacion-de-pantalla-2020-10-09](https://user-images.githubusercontent.com/5584/95591390-86798a00-0a47-11eb-96dd-9c3ac4d0054d.gif)

**Comment by revolist** [comment]
For me right/left arrows used for moving inside of input there, not for switching to the next one... not sure how you can do this.

![Oct-09-2020 23-51-38](https://user-images.githubusercontent.com/64810943/95630464-8b136200-0a8a-11eb-8000-b10b839acca4.gif)

**Comment by kas84** [comment]
That’s when you double click. Try clicking on a cell (no double click),
start typing and then tap the up arrow, for example.

**Comment by kas84** [comment]
Anyway maybe this won't be easy to implement since you are using an actual input (they make it content editable) and it's something that's more lateral, as long as tab and enter work as expected I think it's fair enough.

**Comment by revolist** [comment]
@kas84 just pushed release for tab problem. now it focusing straight on neighbor, not x + 1, y + 1
