### ISSUE TITLE
Weird keyboard event insert "Dead" into the cell when open devTools in browser

### ISSUE THREAD

**Issue by hanzoz** [revolist/revogrid#532]
A bizarre behaviour where the revogrid will insert the "Dead" word to the cell when the user opens devTools in the browser.

[screencast-lngaebamompmckcjpaenfkkdcadjigbo-2024.08.19-20_44_44.webm](https://github.com/user-attachments/assets/a7fc62f6-1271-44f9-a8b2-b0ce0912d8b4)

**Comment by revolist** [comment]
@hanzoz fixed, this behavior was a result of chrome key combination for dev tools. Thank you for reporting it!
