### ISSUE TITLE
Re-rendering Columns with Checkbox Inputs in Selectable Rows

### ISSUE THREAD

**Issue by Karan9615-off** [revolist/revogrid#534]
@m2a2x @revolist

We've implemented a selectable rows table using checkbox inputs within the cellTemplate. The table allows users to select rows via checkboxes, and there's functionality to remove selected rows. However, we're encountering an issue where the checkbox inputs are not updating correctly when rows are removed. Specifically, the checkboxes in the remaining rows do not reflect the updated state after rows have been deleted.

**Problem:**

The checkbox inputs are passed in the cellTemplate of the table.
When rows are removed, the checkbox states are not re-rendered or updated accordingly.
We need a way to ensure that the checkbox cells are refreshed whenever rows are modified.
Question:

How can we re-render or refresh the columns to ensure that the checkbox cells are correctly updated after modifying the rows?

**Steps to Reproduce:**

Implement a table with selectable rows using checkboxes in the cellTemplate.
Add functionality to delete selected rows.
Observe that after deleting rows, the checkboxes in the remaining rows do not update as expected.
Expected Behavior:

Checkbox inputs should re-render and accurately reflect the selection state after any modifications to the rows.

**Current Workaround Attempts:**

We’ve tried manually forcing an update or using slots, but we’re still facing issues with the checkboxes not updating correctly.

**Comment by revolist** [comment]
@Karan9615-off did you close it because of it's done?

**Comment by Karan9615-off** [comment]
Yes, i have handled it locally by indexing for checkboxes. 

But it need to be handled in it.

**Comment by m2a2x** [comment]
To understand the problem we'll need to have some sandbox example. Need to see how you are removing rows etc.
