### ISSUE TITLE
Filtering Dialog Not Working on Firefox

### ISSUE THREAD

**Issue by majkelwork** [revolist/revogrid#535]
**Describe the issue**
I have encountered an issue with the filtering functionality when using Firefox. When attempting to set a filter, nothing happens. This issue does not seem to be present in other browsers like Chrome or Edge.

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/sandbox/vue-grid-date-plugin-forked-nyp72q?file=%2Fsrc%2FApp.vue%3A6%2C25)

**Comment by m2a2x** [comment]
Hi @majkelwork fixed, please verify on the latest version

**Comment by majkelwork** [comment]
> Hi @majkelwork fixed, please verify on the latest version
Everything works fine. Thanks for the quick fix

**Comment by m2a2x** [comment]
> ing works fine. Thanks for the quick fix

Uw!
