### ISSUE TITLE
Error when using vuetify component as editor

### ISSUE THREAD

**Issue by hanzoz** [revolist/revogrid#542]
**Describe the issue**
"Error: [Vuetify] Could not find defaults instance" when I use Vuetify component in the editor component.
<img width="483" alt="image" src="https://github.com/user-attachments/assets/42a8e1f0-a40a-4a2d-9cac-b21ba5f823ef">

[screencast-lngaebamompmckcjpaenfkkdcadjigbo-2024.08.27-23_13_19.webm](https://github.com/user-attachments/assets/94fe24cf-2361-4aef-8c66-728acb51aec0)

This doesn't happened when I use revogrid@3.x.x

**To Reproduce**
Here is the reproduction [link](https://stackblitz.com/edit/vue3-vuetify-starter-seqvn9).

**Comment by m2a2x** [comment]
Hello @hanzoz 
I am checking your problem

**Comment by m2a2x** [comment]
fixed in https://github.com/revolist/vue3-datagrid/pull/48

btw your setup is very old for vite/vue, pls check example here, its working now
https://stackblitz.com/edit/vue3-vuetify-starter-rf8bjg?file=package.json,src%2Fcomponents%2FEditor.vue
