### ISSUE TITLE
cellCompare not working as intended

### ISSUE THREAD

**Issue by ojaylu** [revolist/revogrid#543]
**Describe the issue**
`cellCompare` is not working as intended. `prop` and row are passed as parameters instead of two row values to implement sorting logic.

**To Reproduce**
https://codesandbox.io/p/sandbox/rg-start-standalone-forked-d7hyy2

<img width="293" alt="Screenshot 2024-08-28 at 12 04 07 AM" src="https://github.com/user-attachments/assets/9ee90594-9476-48e7-b97a-dd152176a1ad">
<img width="558" alt="Screenshot 2024-08-28 at 12 03 52 AM" src="https://github.com/user-attachments/assets/405058bb-190e-4a09-bca2-56c7d659e46d">

**Comment by m2a2x** [comment]
Hi @ojaylu!
checking

**Comment by ojaylu** [comment]
I was able to solve it by passing a function with three parameters: (propName, rowData1, rowData2) instead of 2 parameters written in the guide.
https://rv-grid.com/guide/sorting.html

**Comment by m2a2x** [comment]
@ojaylu you are right, I've sent PR to fix docs
Also I've checked it was working always this way as you mentioned above, the docs were wrong on this matter. Too simplified. 

<img width="743" alt="Screenshot 2024-08-28 at 2 39 31 PM" src="https://github.com/user-attachments/assets/c03b8a14-6bfd-48f9-a597-1d9a37ce866c">
