### ISSUE TITLE
How to disable autofill in range mode

### ISSUE THREAD

**Issue by majkelwork** [revolist/revogrid#545]
**Describe the issue**
I've been trying to disable the autofill functionality while using a datagrid with `range` prop. Despite my efforts, I haven't been able to achieve it. Specifically, I attempted to use `event.preventDefault()` within a `beforeautofill` event, but it appears that `beforeautofill` doesn't return an event.

**To Reproduce**
 [Using e.preventDefault()](https://codesandbox.io/p/sandbox/vue-grid-date-plugin-forked-rf766y)

**Comment by m2a2x** [comment]
@majkelwork seems like compiler issue, I am going to change it to the state it was before, so you will get full event instead of details (data only)

**Comment by revolist** [comment]
@majkelwork 
https://codesandbox.io/p/sandbox/vue-grid-date-plugin-forked-tp442j?file=%2Fpackage.json
now it's going to work as expected
