### ISSUE TITLE
Custom Editors

### ISSUE THREAD

**Issue by kas84** [revolist/revogrid#55]
Do you have any examples on setting up a datepicker or any other custom component as a cell editor?

**Comment by revolist** [comment]
@kas84 not yet, we have a way to apply any 3rd party editor
https://revolist.github.io/revogrid/?path=/docs/docs-custom-editor--page

You can apply any 3rd party component you'd like.
We have it planned for the next release to support several types: input, datepicker, select, multiselect.

**Comment by kas84** [comment]
Would be great to have a select with search functionality like the image I attach.
Would be awesome if there's an option to make it editable on one single click or at least that on type it would start searching on the select options.

![1_Ag2lbKhZ5zOaJcBb1SU3jw](https://user-images.githubusercontent.com/5584/94988185-bf0ef480-056b-11eb-8aca-68e1ae451713.gif)

**Comment by bbbford** [comment]
> @kas84 not yet, we have a way to apply any 3rd party editor
> https://revolist.github.io/revogrid/?path=/docs/docs-custom-editor--page
> 
> You can apply any 3rd party component you'd like.
> We have it planned for the next release to support several types: input, datepicker, select, multiselect.

Looking forward to next release! Keep up the great work!

**Comment by revolist** [comment]
https://revolist.github.io/revogrid/guide/column.types.html
select, string, number added

**Comment by kas84** [comment]
The columnType Number doesn't have an editor, does it? And in that case, shouldn't the input should have an input type="number", because you care about that when you edit a cell and type a "4", it's actually a number and not a string.

**Comment by mikproto** [comment]
@kas84 thank you for the comment.
Number type has render only specification, editor can be quite specific per project. And it'll require validators etc.
We have multiple huge projects running on grid where we need to allow enter anything and parse it on our side.

Also you are always welcome to provide improved solution or even separate column number plugin which we'll include in our main description, thank you in advance.

**Comment by revolist** [comment]
Date(editor), Select(renderer/editor), Number(as render) added.
Plugin system added. 

Read docs for more information:
https://revolist.github.io/revogrid/guide/column.types.html

**Comment by kas84** [comment]
The select type cell won't work as it is for the on Tab behaviour, like the text editor currently does. Would you be open to integrate a pull request for both revogrid-column-select and revo-dropdown?

On revogrid-column-select I had to add originalEvent into the types because although it was already passed, it wasn't on the types and at least vscode wouldn't allow me to check originalEvent because ObjectChange and ArrayChange didn't have it in their types.

<img width="669" alt="Captura de pantalla 2020-11-25 a las 14 45 38" src="https://user-images.githubusercontent.com/5584/100237089-bd8bf800-2f2e-11eb-97db-87bd8ae554c4.png">

<img width="598" alt="Captura de pantalla 2020-11-25 a las 14 46 19" src="https://user-images.githubusercontent.com/5584/100237100-c11f7f00-2f2e-11eb-8a1d-f5cd9a48f7eb.png">

**Comment by revolist** [comment]
Hey @kas84 , I’ll be happy to review your request, please send me when you can.

**Comment by kas84** [comment]
Done in both projects

Thanks for this amazing component :)

**Comment by revolist** [comment]
@kas84 merged, sorry for the delay. Publishing now.
