### ISSUE TITLE
[vitepress] Pre-transform error: parsing revogrid-docs/pro-pages/tsconfig.json failed: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Thoemmy** [revolist/revogrid#558]
**Describe the issue**
I synced the actual changes from revogrid-docs to my fork and i am now getting this error which is related to the pro-pages which are not accessible because they are in a repo we cannot access.

**Comment by m2a2x** [comment]
Hi @Thoemmy 
Makes sense, will remove soon

**Comment by m2a2x** [comment]
@Thoemmy done
https://github.com/revolist/revogrid-docs/pull/6
