### ISSUE TITLE
@revolist/revogrid-column-date is hidden when the page height is insufficient to display it.

### ISSUE THREAD

**Issue by windxnd** [revolist/revogrid#568]
@revolist 

i am using @revolist/revogrid-column-date": "^2.0.21" and @revolist/revogrid: "^4.10.6", date picker is hidden when the page height is insufficient to display it.

evidence is in the attached image.

the demo version is also experiencing the same issue.

please help me.

https://rv-grid.com/demo/

![image](https://github.com/user-attachments/assets/2a1efa7e-5895-4923-84b1-f7900d0e930e)

**Comment by m2a2x** [comment]
hi @windxnd, will check later today

**Comment by windxnd** [comment]
@m2a2x 
i am still waiting, do you have any new information?

**Comment by m2a2x** [comment]
hi @windxnd 
Yes, I would need to improve date plugin so it would open datepicker up when it reach the end or find another way to scroll it with body.

**Comment by m2a2x** [comment]
hi @windxnd 
made you a fix

https://github.com/revolist/revogrid-column-date/pull/34
