### ISSUE TITLE
Integration with TanStack Example

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#597]
TanStack growing popularity requires some attention.

This task involves creating simple examples to demonstrate how to integrate TanStack with RevoGrid in both Vue and React. The integration will showcase how to leverage TanStack functions to extend the functionality of the grid, enhancing user interactions and data management capabilities.

### Objectives

- **React Example:**
  - Set up a RevoGrid instance that utilizes TanStack for data handling.
  - Implement sorting and filtering functionalities using TanStack's features.
  - Ensure the example is clear and easy to understand for developers.

- **Vue Example:**
  - Create a Vue component that integrates RevoGrid with TanStack.
  - Demonstrate how to apply TanStack's capabilities to manage grid data effectively.
  - Provide clear documentation for developers to follow.

### Acceptance Criteria

- Both examples must demonstrate basic functionality, including displaying data, sorting, and filtering.
- The code should be well-documented, explaining how TanStack enhances RevoGrid’s capabilities.
- Ensure that the examples are functional and tested in their respective environments (Vue and React).

### Additional Notes

- Consider including links to the TanStack documentation for further reference.
- Aim for simplicity in the examples to make them accessible for developers who are new to both TanStack and RevoGrid.

**Comment by m2a2x** [comment]
https://github.com/revolist/revogrid-docs/pull/10

**Comment by m2a2x** [comment]
https://rv-grid.com/guide/tanstack/
