### ISSUE TITLE
Bottom horizontal scrollbar sometimes overlays content, blocking clicks

### ISSUE THREAD

**Issue by Techn1x** [revolist/revogrid#601]
**Describe the issue**
The horizontal scroll at the bottom of the container seems to somehow, sometimes, block clicks on grid cells of the bottom row, despite not actually being visible. Usually, it can be reproduced by moving the mouse up from the bottom of the grid.

https://github.com/user-attachments/assets/5224c950-959f-4757-9412-26228bde65ec

**To Reproduce**

I added a size to the grid and a couple of rows to make sure we hit the bottom of the container.

I don't think it matters, but I'm on firefox.

https://codesandbox.io/p/sandbox/rg-start-standalone-forked-3vzwhm

**Comment by Techn1x** [comment]
hey @m2a2x any luck on this one? happy to help out if you need

**Comment by m2a2x** [comment]
hi @Techn1x 
thanks for the help offer, I would gladly take it.

I am thinking that showing scroll bar on hover over was an over engineering. I believe this would be the fix to remove it.

Will provide PR soon.

**Comment by m2a2x** [comment]
https://github.com/revolist/revogrid/pull/628

**Comment by Techn1x** [comment]
thanks for this btw
