### ISSUE TITLE
@revolist/revogrid-column-select - the value of the input is not highlighted with a different background color in dropdown

### ISSUE THREAD

**Issue by RK-cuongnq** [revolist/revogrid#602]
@revolist @m2a2x
I am using @revolist/revogrid: "^4.10.6" and "@revolist/revogrid-column-select": "^3.1.5" to use the select/dropdown in my project. However, when the dropdown opens, the value of the input is not highlighted with a different background color in dropdown, and the highlight is always on the first element.

I want to ask if there's a way to highlight the input value when the dropdown opens?

evidence is in the attached image.

the demo version is also experiencing the same issue.

https://rv-grid.com/demo/

![image](https://github.com/user-attachments/assets/72a275cd-e502-4f5e-aa84-775c82715949)

![image](https://github.com/user-attachments/assets/9a0c4d29-3728-4657-9d73-89b96fb9819e)

**Comment by m2a2x** [comment]
hi @RK-cuongnq, @revolist/revogrid-column-select": "^3.1.7" should support what you've asked about.
