### ISSUE TITLE
Missing border between row header & stacked/grouped header (default theme)

### ISSUE THREAD

**Issue by Techn1x** [revolist/revogrid#608]
**Describe the issue**

There's no border between the row headers and the "A" grouped column

![Screenshot 2024-10-23 at 12 07 36 pm](https://github.com/user-attachments/assets/f6d2eee1-0ed4-4ec7-8c40-9f23b9873d73)

**To Reproduce**

https://codesandbox.io/p/sandbox/rg-start-standalone-forked-l7cnjd

I think it's becase the "grouped row header" doesn't get a cell "rgHeaderCell" which is what applies the box-shadow border. Not sure how to get one in there

You can see in the DOM here the difference between the two row headers.
![Screenshot 2024-10-23 at 12 15 35 pm](https://github.com/user-attachments/assets/1f7a8e2a-aff1-40f8-b1fd-f30353cd7248)

**Comment by m2a2x** [comment]
Fixed
