### ISSUE TITLE
Lazy rendering mode let checkbox Single choice becomes multiple choice

### ISSUE THREAD

**Issue by hobbitwu** [revolist/revogrid#609]
@revolist 

**Describe the issue**
I'm useing "@revolist/vue3-datagrid": "4.10.20" had this problem.(before use 3.6.17)
Check on the [Vue 3 Select Example](https://rv-grid.com/demo/vue/vue.select.html) has the same bug.
Lazy rendering mode let checkbox Single choice becomes multiple choice.

https://github.com/user-attachments/assets/61e338ef-0543-415f-8195-c1b9a5940a80

**To Reproduce**
The first select on the lazy rendering please(20-30).
And then select single checkbox will be multiple choice.

Now I use disableVirtualY="true", disableVirtualX="true" to fix this problem but this setting can not show the scroll bar.
Could I use disableVirtualY/disableVirtualX with the scroll bar?
Please help me.

**Comment by revolist** [comment]
Thank you for pointing out the issue in the example.
The trick was to add key so vnode would not be confused with previous one

```
cellTemplate: (h, { model, prop, rowIndex }) => {
                const inputVNode = h('input', {
                    type: 'checkbox',
                    key: rowIndex, // need uniq key
                    checked: model.selected || undefined,
                    onChange: (e) => selectSingle(model, e.target.checked),
                })
                return h('label', undefined, inputVNode, model[prop])
            },
```
