### ISSUE TITLE
Import data from excel

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#64]

**Comment by mariusa** [comment]
How does this work? Don't see it mentioned in README

**Comment by revolist** [comment]
Hello @mariusa 
To import, you have to do copy-paste. Just copy a table with cntrl + c and paste with cntrl + v.
If you need something specific please provide examples and case scenarios we will add it as a feature.

**Comment by mariusa** [comment]
I see, thanks! Should this be closed?

**Comment by revolist** [comment]
Yep, @mariusa closing now. Thank you for your question.
If you see other concerns or have some idea to realize this in another way - let us know. I'll check it out.

**Comment by rrggrr** [comment]
Would like to see ability to import and render .csv data via file upload and/or API call.

**Comment by revolist** [comment]
@rrggrr what you are suggesting is to provide kind of plugin which will allow blob import from csv?

**Comment by rrggrr** [comment]
Correct, upload .csv file instead of copying & pasting. If development bounties are of interest reach out.

> @rrggrr what you are suggesting is to provide kind of plugin which will allow blob import from csv?
