### ISSUE TITLE
Attribution - open in new tab

### ISSUE THREAD

**Issue by Techn1x** [revolist/revogrid#667]
Hi! Just wondering if the attribution link can be made to open in a new tab - opening in the same tab means the user will lose all their work on the page (any data that was input into the grid + other fields that are on the page)

I understand if you want to keep it as is though, as more incentive to pay for the product. Though there are plenty of reasons to pay already (like the long list of pro plugins, improved support, and ethical removal of the attribution) :)

**Comment by m2a2x** [comment]
Hi @Techn1x, I agree it makes sense. Could you make PR for it?

**Comment by Techn1x** [comment]
Sure thing!

**Comment by Techn1x** [comment]
done! https://github.com/revolist/revogrid/pull/670
