### ISSUE TITLE
Columns drag and drop

### ISSUE THREAD

**Issue by revolist** [revolist/revogrid#99]

**Comment by Tadeu17** [comment]
Hey! Where is this relatively to the roadmap?

**Comment by revolist** [comment]
Hello,

Relatively it should be after:
- and advanced column grouping
- tree data view

**Comment by stuta** [comment]
Does this mean that you can re-order columns with drag and drop?

**Comment by revolist** [comment]
Yes, this was a plan

**Comment by chrisoprea** [comment]
any changes?

**Comment by mattiaslvv** [comment]
Any updates on this?

**Comment by anthonyboutinov** [comment]
Has anyone managed to create a working version of draggable columns themselves for RevoGrid?

**Comment by m2a2x** [comment]
Hey everyone it's done
just not documented yet

**Comment by m2a2x** [comment]
https://github.com/revolist/revogrid/blob/master/src/components/revo-grid/readme.md
check for canMoveColumns

**Comment by hobbitwu** [comment]
I used canMoveColumns then use getColumns() in columnDragEnd event, but columns didn't change.
How do I get the columns after the change of order?

**Comment by oak-h-test** [comment]
> I used canMoveColumns then use getColumns() in columnDragEnd event, but columns didn't change. How do I get the columns after the change of order?

beforecolumndragend detail have relevant information, but not the full new columns definition.

**Comment by hobbitwu** [comment]
> > I used canMoveColumns then use getColumns() in columnDragEnd event, but columns didn't change. How do I get the columns after the change of order?
> 
> beforecolumndragend detail have relevant information, but not the full new columns definition.

I'm has been solved! Thanks!
